/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GetEnumMetadataRequestBuilderRequestsMetadata, type GetEnumMetadataRequestBuilder } from './getEnumMetadata/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/EnumMetadata
 */
export interface EnumMetadataRequestBuilder extends BaseRequestBuilder<EnumMetadataRequestBuilder> {
    /**
     * The GetEnumMetadata property
     */
    get getEnumMetadata(): GetEnumMetadataRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const EnumMetadataRequestBuilderUriTemplate = "{+baseurl}/Api/EnumMetadata";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EnumMetadataRequestBuilderNavigationMetadata: Record<Exclude<keyof EnumMetadataRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    getEnumMetadata: {
        requestsMetadata: GetEnumMetadataRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
