/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageResultDtoOfRecognitionUsageSummaryReadModelFromDiscriminatorValue, serializeBranchRecognitionUsageSummaryQueryRequest, serializePageResultDtoOfRecognitionUsageSummaryReadModel, type BranchRecognitionUsageSummaryQueryRequest, type PageResultDtoOfRecognitionUsageSummaryReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryBranchRecognitionUsageSummary
 */
export interface QueryBranchRecognitionUsageSummaryRequestBuilder extends BaseRequestBuilder<QueryBranchRecognitionUsageSummaryRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageResultDtoOfRecognitionUsageSummaryReadModel>}
     */
     post(body: BranchRecognitionUsageSummaryQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PageResultDtoOfRecognitionUsageSummaryReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BranchRecognitionUsageSummaryQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryBranchRecognitionUsageSummaryRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryBranchRecognitionUsageSummary";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryBranchRecognitionUsageSummaryRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryBranchRecognitionUsageSummaryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPageResultDtoOfRecognitionUsageSummaryReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBranchRecognitionUsageSummaryQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
