/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRecognitionProjectConfigurationReadModelFromDiscriminatorValue, serializeRecognitionProjectConfigurationListQueryRequest, serializeRecognitionProjectConfigurationReadModel, type RecognitionProjectConfigurationListQueryRequest, type RecognitionProjectConfigurationReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryRecognitionProjectConfigurationList
 */
export interface QueryRecognitionProjectConfigurationListRequestBuilder extends BaseRequestBuilder<QueryRecognitionProjectConfigurationListRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecognitionProjectConfigurationReadModel[]>}
     */
     post(body: RecognitionProjectConfigurationListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecognitionProjectConfigurationReadModel[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RecognitionProjectConfigurationListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryRecognitionProjectConfigurationListRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryRecognitionProjectConfigurationList";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryRecognitionProjectConfigurationListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryRecognitionProjectConfigurationListRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createRecognitionProjectConfigurationReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRecognitionProjectConfigurationListQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
