/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageResultDtoOfSourceRecognitionSummaryReadModelFromDiscriminatorValue, serializePageResultDtoOfSourceRecognitionSummaryReadModel, serializeSourceRecognitionSummaryQueryRequest, type PageResultDtoOfSourceRecognitionSummaryReadModel, type SourceRecognitionSummaryQueryRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QuerySourceRecognitionSummary
 */
export interface QuerySourceRecognitionSummaryRequestBuilder extends BaseRequestBuilder<QuerySourceRecognitionSummaryRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageResultDtoOfSourceRecognitionSummaryReadModel>}
     */
     post(body: SourceRecognitionSummaryQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PageResultDtoOfSourceRecognitionSummaryReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SourceRecognitionSummaryQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QuerySourceRecognitionSummaryRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QuerySourceRecognitionSummary";
/**
 * Metadata for all the requests in the request builder.
 */
export const QuerySourceRecognitionSummaryRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QuerySourceRecognitionSummaryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPageResultDtoOfSourceRecognitionSummaryReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSourceRecognitionSummaryQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
