/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PdfRequestBuilderRequestsMetadata, type PdfRequestBuilder } from './pdf/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/report-pdf/{reportId}/versions/{reportVersionId}
 */
export interface WithReportVersionItemRequestBuilder extends BaseRequestBuilder<WithReportVersionItemRequestBuilder> {
    /**
     * The pdf property
     */
    get pdf(): PdfRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithReportVersionItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/report-pdf/{reportId}/versions/{reportVersionId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithReportVersionItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithReportVersionItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    pdf: {
        requestsMetadata: PdfRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
