/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BranchRequestBuilderRequestsMetadata, type BranchRequestBuilder } from './branch/index.js';
// @ts-ignore
import { PlatformRequestBuilderRequestsMetadata, type PlatformRequestBuilder } from './platform/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/statistics-export
 */
export interface StatisticsExportRequestBuilder extends BaseRequestBuilder<StatisticsExportRequestBuilder> {
    /**
     * The branch property
     */
    get branch(): BranchRequestBuilder;
    /**
     * The platform property
     */
    get platform(): PlatformRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const StatisticsExportRequestBuilderUriTemplate = "{+baseurl}/api/v1/statistics-export";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StatisticsExportRequestBuilderNavigationMetadata: Record<Exclude<keyof StatisticsExportRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    branch: {
        requestsMetadata: BranchRequestBuilderRequestsMetadata,
    },
    platform: {
        requestsMetadata: PlatformRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
