/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageResultDtoOfSourceRecognitionDetailReadModelFromDiscriminatorValue, serializeBranchSourceRecognitionDetailsQueryRequest, serializePageResultDtoOfSourceRecognitionDetailReadModel, type BranchSourceRecognitionDetailsQueryRequest, type PageResultDtoOfSourceRecognitionDetailReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryBranchSourceRecognitionDetails
 */
export interface QueryBranchSourceRecognitionDetailsRequestBuilder extends BaseRequestBuilder<QueryBranchSourceRecognitionDetailsRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageResultDtoOfSourceRecognitionDetailReadModel>}
     */
     post(body: BranchSourceRecognitionDetailsQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PageResultDtoOfSourceRecognitionDetailReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BranchSourceRecognitionDetailsQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryBranchSourceRecognitionDetailsRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryBranchSourceRecognitionDetails";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryBranchSourceRecognitionDetailsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryBranchSourceRecognitionDetailsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPageResultDtoOfSourceRecognitionDetailReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBranchSourceRecognitionDetailsQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
