/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRecognitionMatchesResponseReadModelFromDiscriminatorValue, serializeRecognitionMatchesResponseReadModel, serializeRecognitionMatchQueryRequest, type RecognitionMatchesResponseReadModel, type RecognitionMatchQueryRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReport/RequestRecognitionMatches
 */
export interface RequestRecognitionMatchesRequestBuilder extends BaseRequestBuilder<RequestRecognitionMatchesRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecognitionMatchesResponseReadModel>}
     */
     post(body: RecognitionMatchQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecognitionMatchesResponseReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RecognitionMatchQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RequestRecognitionMatchesRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReport/RequestRecognitionMatches";
/**
 * Metadata for all the requests in the request builder.
 */
export const RequestRecognitionMatchesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RequestRecognitionMatchesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createRecognitionMatchesResponseReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRecognitionMatchQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
