/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageResultDtoOfRecognitionUsageSummaryReadModelFromDiscriminatorValue, serializePageResultDtoOfRecognitionUsageSummaryReadModel, serializeRecognitionUsageSummaryQueryRequest, type PageResultDtoOfRecognitionUsageSummaryReadModel, type RecognitionUsageSummaryQueryRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryRecognitionUsageSummary
 */
export interface QueryRecognitionUsageSummaryRequestBuilder extends BaseRequestBuilder<QueryRecognitionUsageSummaryRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageResultDtoOfRecognitionUsageSummaryReadModel>}
     */
     post(body: RecognitionUsageSummaryQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PageResultDtoOfRecognitionUsageSummaryReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RecognitionUsageSummaryQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryRecognitionUsageSummaryRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryRecognitionUsageSummary";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryRecognitionUsageSummaryRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryRecognitionUsageSummaryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPageResultDtoOfRecognitionUsageSummaryReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRecognitionUsageSummaryQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
