/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMedicalStandardCategoryListReadModelFromDiscriminatorValue, serializeMedicalStandardCategoryListQueryRequest, serializeMedicalStandardCategoryListReadModel, type MedicalStandardCategoryListQueryRequest, type MedicalStandardCategoryListReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryMedicalStandardCategoryList
 */
export interface QueryMedicalStandardCategoryListRequestBuilder extends BaseRequestBuilder<QueryMedicalStandardCategoryListRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MedicalStandardCategoryListReadModel[]>}
     */
     post(body: MedicalStandardCategoryListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MedicalStandardCategoryListReadModel[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MedicalStandardCategoryListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryMedicalStandardCategoryListRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryMedicalStandardCategoryList";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryMedicalStandardCategoryListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryMedicalStandardCategoryListRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createMedicalStandardCategoryListReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMedicalStandardCategoryListQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
