/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageResultDtoOfMedicalReportListReadModelFromDiscriminatorValue, serializePageResultDtoOfMedicalReportListReadModel, serializeReportListQueryRequest, type PageResultDtoOfMedicalReportListReadModel, type ReportListQueryRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryMedicalReportList
 */
export interface QueryMedicalReportListRequestBuilder extends BaseRequestBuilder<QueryMedicalReportListRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageResultDtoOfMedicalReportListReadModel>}
     */
     post(body: ReportListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PageResultDtoOfMedicalReportListReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ReportListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryMedicalReportListRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryMedicalReportList";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryMedicalReportListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryMedicalReportListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPageResultDtoOfMedicalReportListReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeReportListQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
