/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEffectiveMedicalStandardCatalogReadModelFromDiscriminatorValue, serializeEffectiveMedicalStandardCatalogQueryRequest, serializeEffectiveMedicalStandardCatalogReadModel, type EffectiveMedicalStandardCatalogQueryRequest, type EffectiveMedicalStandardCatalogReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryEffectiveMedicalStandardCatalog
 */
export interface QueryEffectiveMedicalStandardCatalogRequestBuilder extends BaseRequestBuilder<QueryEffectiveMedicalStandardCatalogRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EffectiveMedicalStandardCatalogReadModel>}
     */
     post(body: EffectiveMedicalStandardCatalogQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EffectiveMedicalStandardCatalogReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: EffectiveMedicalStandardCatalogQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryEffectiveMedicalStandardCatalogRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryEffectiveMedicalStandardCatalog";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryEffectiveMedicalStandardCatalogRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryEffectiveMedicalStandardCatalogRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createEffectiveMedicalStandardCatalogReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeEffectiveMedicalStandardCatalogQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
