/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMedicalReportVersionDetailQueryReadModelFromDiscriminatorValue, serializeMedicalReportVersionDetailQueryReadModel, serializeMedicalReportVersionDetailQueryRequest, type MedicalReportVersionDetailQueryReadModel, type MedicalReportVersionDetailQueryRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryMedicalReportVersionDetail
 */
export interface QueryMedicalReportVersionDetailRequestBuilder extends BaseRequestBuilder<QueryMedicalReportVersionDetailRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MedicalReportVersionDetailQueryReadModel>}
     */
     post(body: MedicalReportVersionDetailQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MedicalReportVersionDetailQueryReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MedicalReportVersionDetailQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryMedicalReportVersionDetailRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryMedicalReportVersionDetail";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryMedicalReportVersionDetailRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryMedicalReportVersionDetailRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createMedicalReportVersionDetailQueryReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMedicalReportVersionDetailQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
