-- postgresql schema
create table if not exists examination_report_content (
  id uuid not null,
  report_version_id uuid not null,
  source_examination_type_code varchar(100),
  source_examination_type_name varchar(100),
  report_remark text,
  overall_abnormal_flag varchar(100),
  findings text not null,
  conclusion text not null,
  condition_description text,
  examination_purpose text,
  source_diagnosis_code varchar(100),
  source_diagnosis_name varchar(100) not null,
  examination_time timestamp without time zone not null,
  examiner_id varchar(100) not null,
  examiner_name varchar(100) not null,
  source_image_status integer not null,
  image_access_url varchar(100),
  examination_method varchar(100),
  device_code varchar(100),
  device_name varchar(100),
  oper_id uuid not null,
  oper_time timestamptz not null,
  primary key (id)
);
