-- postgresql schema
create table if not exists medical_report_version (
  id uuid not null,
  report_id uuid not null,
  patient_id uuid not null,
  version_number integer not null,
  source_report_name varchar(100) not null,
  patient_name varchar(100) not null,
  patient_gender_code varchar(100) not null,
  patient_birth_date timestamp without time zone not null,
  patient_phone_number varchar(100),
  age_at_report varchar(100),
  identity_document_type_code varchar(100) not null,
  identity_document_no varchar(100) not null,
  visit_type integer not null,
  visit_serial_no varchar(100) not null,
  application_dept_id varchar(100) not null,
  application_dept_name varchar(100) not null,
  application_doctor_id varchar(100) not null,
  application_doctor_name varchar(100) not null,
  execution_dept_id varchar(100) not null,
  execution_dept_name varchar(100) not null,
  report_dept_id varchar(100) not null,
  report_dept_name varchar(100) not null,
  report_doctor_id varchar(100) not null,
  report_doctor_name varchar(100) not null,
  review_doctor_id varchar(100) not null,
  review_doctor_name varchar(100) not null,
  review_time timestamp without time zone,
  inpatient_no varchar(100),
  ward_name varchar(100),
  room_name varchar(100),
  bed_no varchar(100),
  application_time timestamp without time zone not null,
  report_time timestamp without time zone not null,
  source_modified_time timestamp without time zone not null,
  received_time timestamp without time zone not null,
  pdf_file_id varchar(100) not null,
  pdf_file_name varchar(100) not null,
  source_confidential_flag varchar(100),
  oper_id uuid not null,
  oper_time timestamptz not null,
  primary key (id)
);
