/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageResultDtoOfSourceRecognitionDetailReadModelFromDiscriminatorValue, serializePageResultDtoOfSourceRecognitionDetailReadModel, serializeSourceRecognitionDetailsQueryRequest, type PageResultDtoOfSourceRecognitionDetailReadModel, type SourceRecognitionDetailsQueryRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QuerySourceRecognitionDetails
 */
export interface QuerySourceRecognitionDetailsRequestBuilder extends BaseRequestBuilder<QuerySourceRecognitionDetailsRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageResultDtoOfSourceRecognitionDetailReadModel>}
     */
     post(body: SourceRecognitionDetailsQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PageResultDtoOfSourceRecognitionDetailReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SourceRecognitionDetailsQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QuerySourceRecognitionDetailsRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QuerySourceRecognitionDetails";
/**
 * Metadata for all the requests in the request builder.
 */
export const QuerySourceRecognitionDetailsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QuerySourceRecognitionDetailsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPageResultDtoOfSourceRecognitionDetailReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSourceRecognitionDetailsQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
