/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { EnumMetadataRequestBuilderNavigationMetadata, type EnumMetadataRequestBuilder } from './enumMetadata/index.js';
// @ts-ignore
import { MedicalRecognitionReportRequestBuilderNavigationMetadata, type MedicalRecognitionReportRequestBuilder } from './medicalRecognitionReport/index.js';
// @ts-ignore
import { MedicalRecognitionReportQueryRequestBuilderNavigationMetadata, type MedicalRecognitionReportQueryRequestBuilder } from './medicalRecognitionReportQuery/index.js';
// @ts-ignore
import { type V1RequestBuilder, V1RequestBuilderNavigationMetadata } from './v1/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The EnumMetadata property
     */
    get enumMetadata(): EnumMetadataRequestBuilder;
    /**
     * The MedicalRecognitionReport property
     */
    get medicalRecognitionReport(): MedicalRecognitionReportRequestBuilder;
    /**
     * The MedicalRecognitionReportQuery property
     */
    get medicalRecognitionReportQuery(): MedicalRecognitionReportQueryRequestBuilder;
    /**
     * The v1 property
     */
    get v1(): V1RequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    enumMetadata: {
        navigationMetadata: EnumMetadataRequestBuilderNavigationMetadata,
    },
    medicalRecognitionReport: {
        navigationMetadata: MedicalRecognitionReportRequestBuilderNavigationMetadata,
    },
    medicalRecognitionReportQuery: {
        navigationMetadata: MedicalRecognitionReportQueryRequestBuilderNavigationMetadata,
    },
    v1: {
        navigationMetadata: V1RequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
