/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MedicalRecognitionReportRequestBuilderNavigationMetadata, type MedicalRecognitionReportRequestBuilder } from './medicalRecognitionReport/index.js';
// @ts-ignore
import { MedicalRecognitionReportQueryRequestBuilderNavigationMetadata, type MedicalRecognitionReportQueryRequestBuilder } from './medicalRecognitionReportQuery/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The MedicalRecognitionReport property
     */
    get medicalRecognitionReport(): MedicalRecognitionReportRequestBuilder;
    /**
     * The MedicalRecognitionReportQuery property
     */
    get medicalRecognitionReportQuery(): MedicalRecognitionReportQueryRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/Api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    medicalRecognitionReport: {
        navigationMetadata: MedicalRecognitionReportRequestBuilderNavigationMetadata,
    },
    medicalRecognitionReportQuery: {
        navigationMetadata: MedicalRecognitionReportQueryRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
