/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRecognitionCitationDetailReadModelFromDiscriminatorValue, serializeRecognitionCitationDetailReadModel, serializeRecognitionCitationDetailRequest, type RecognitionCitationDetailReadModel, type RecognitionCitationDetailRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryRecognitionCitationDetail
 */
export interface QueryRecognitionCitationDetailRequestBuilder extends BaseRequestBuilder<QueryRecognitionCitationDetailRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecognitionCitationDetailReadModel>}
     */
     post(body: RecognitionCitationDetailRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecognitionCitationDetailReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RecognitionCitationDetailRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryRecognitionCitationDetailRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryRecognitionCitationDetail";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryRecognitionCitationDetailRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryRecognitionCitationDetailRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createRecognitionCitationDetailReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRecognitionCitationDetailRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
