<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Dy.Base.Application.Contracts" Version="1.0.0.184" />
    <PackageVersion Include="Dy.Core.Abstractions" Version="1.1.0.54" />
    <PackageVersion Include="Dy.Core.Extensions" Version="1.1.0.54" />
    <PackageVersion Include="Dy.Core.SourceGen" Version="1.0.0.66" />
    <PackageVersion Include="Dy.CompileToolkit.Version" Version="3.1.0.5" />
    <PackageVersion Include="Dy.Apron.Abstractions" Version="1.1.0.48" />
    <PackageVersion Include="Dy.Apron.Bridge" Version="1.1.0.48" />
    <PackageVersion Include="Dy.Apron.QuickStart" Version="1.1.0.48" />
    <PackageVersion Include="Dy.Apron.Security" Version="1.1.0.48" />
    <PackageVersion Include="Dy.Earthrace.Abstractions" Version="1.0.0.60" />
    <PackageVersion Include="Dy.Earthrace" Version="1.0.0.60" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Dy.Plugin.AspNet.Scalar" Version="0.2.0.16" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>