/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type VersionsRequestBuilder, VersionsRequestBuilderNavigationMetadata } from './versions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/report-pdf/{reportId}
 */
export interface WithReportItemRequestBuilder extends BaseRequestBuilder<WithReportItemRequestBuilder> {
    /**
     * The versions property
     */
    get versions(): VersionsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithReportItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/report-pdf/{reportId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithReportItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithReportItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    versions: {
        navigationMetadata: VersionsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
