/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { QueryBranchMedicalReportListRequestBuilderRequestsMetadata, type QueryBranchMedicalReportListRequestBuilder } from './queryBranchMedicalReportList/index.js';
// @ts-ignore
import { QueryBranchRecognitionAmountListRequestBuilderRequestsMetadata, type QueryBranchRecognitionAmountListRequestBuilder } from './queryBranchRecognitionAmountList/index.js';
// @ts-ignore
import { QueryBranchRecognitionUsageDetailsRequestBuilderRequestsMetadata, type QueryBranchRecognitionUsageDetailsRequestBuilder } from './queryBranchRecognitionUsageDetails/index.js';
// @ts-ignore
import { QueryBranchRecognitionUsageSummaryRequestBuilderRequestsMetadata, type QueryBranchRecognitionUsageSummaryRequestBuilder } from './queryBranchRecognitionUsageSummary/index.js';
// @ts-ignore
import { QueryBranchSourceRecognitionDetailsRequestBuilderRequestsMetadata, type QueryBranchSourceRecognitionDetailsRequestBuilder } from './queryBranchSourceRecognitionDetails/index.js';
// @ts-ignore
import { QueryBranchSourceRecognitionSummaryRequestBuilderRequestsMetadata, type QueryBranchSourceRecognitionSummaryRequestBuilder } from './queryBranchSourceRecognitionSummary/index.js';
// @ts-ignore
import { QueryEffectiveMedicalStandardCatalogRequestBuilderRequestsMetadata, type QueryEffectiveMedicalStandardCatalogRequestBuilder } from './queryEffectiveMedicalStandardCatalog/index.js';
// @ts-ignore
import { QueryMedicalReportListRequestBuilderRequestsMetadata, type QueryMedicalReportListRequestBuilder } from './queryMedicalReportList/index.js';
// @ts-ignore
import { QueryMedicalReportVersionDetailRequestBuilderRequestsMetadata, type QueryMedicalReportVersionDetailRequestBuilder } from './queryMedicalReportVersionDetail/index.js';
// @ts-ignore
import { QueryMedicalReportVersionListRequestBuilderRequestsMetadata, type QueryMedicalReportVersionListRequestBuilder } from './queryMedicalReportVersionList/index.js';
// @ts-ignore
import { QueryMedicalStandardCategoryListRequestBuilderRequestsMetadata, type QueryMedicalStandardCategoryListRequestBuilder } from './queryMedicalStandardCategoryList/index.js';
// @ts-ignore
import { QueryMedicalStandardGroupListRequestBuilderRequestsMetadata, type QueryMedicalStandardGroupListRequestBuilder } from './queryMedicalStandardGroupList/index.js';
// @ts-ignore
import { QueryMedicalStandardItemListRequestBuilderRequestsMetadata, type QueryMedicalStandardItemListRequestBuilder } from './queryMedicalStandardItemList/index.js';
// @ts-ignore
import { QueryRecognitionAmountListRequestBuilderRequestsMetadata, type QueryRecognitionAmountListRequestBuilder } from './queryRecognitionAmountList/index.js';
// @ts-ignore
import { QueryRecognitionCitationDetailRequestBuilderRequestsMetadata, type QueryRecognitionCitationDetailRequestBuilder } from './queryRecognitionCitationDetail/index.js';
// @ts-ignore
import { QueryRecognitionMatchRecordRequestBuilderRequestsMetadata, type QueryRecognitionMatchRecordRequestBuilder } from './queryRecognitionMatchRecord/index.js';
// @ts-ignore
import { QueryRecognitionProjectConfigurationListRequestBuilderRequestsMetadata, type QueryRecognitionProjectConfigurationListRequestBuilder } from './queryRecognitionProjectConfigurationList/index.js';
// @ts-ignore
import { QueryRecognitionUsageDetailsRequestBuilderRequestsMetadata, type QueryRecognitionUsageDetailsRequestBuilder } from './queryRecognitionUsageDetails/index.js';
// @ts-ignore
import { QueryRecognitionUsageSummaryRequestBuilderRequestsMetadata, type QueryRecognitionUsageSummaryRequestBuilder } from './queryRecognitionUsageSummary/index.js';
// @ts-ignore
import { QuerySourceRecognitionDetailsRequestBuilderRequestsMetadata, type QuerySourceRecognitionDetailsRequestBuilder } from './querySourceRecognitionDetails/index.js';
// @ts-ignore
import { QuerySourceRecognitionSummaryRequestBuilderRequestsMetadata, type QuerySourceRecognitionSummaryRequestBuilder } from './querySourceRecognitionSummary/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery
 */
export interface MedicalRecognitionReportQueryRequestBuilder extends BaseRequestBuilder<MedicalRecognitionReportQueryRequestBuilder> {
    /**
     * The QueryBranchMedicalReportList property
     */
    get queryBranchMedicalReportList(): QueryBranchMedicalReportListRequestBuilder;
    /**
     * The QueryBranchRecognitionAmountList property
     */
    get queryBranchRecognitionAmountList(): QueryBranchRecognitionAmountListRequestBuilder;
    /**
     * The QueryBranchRecognitionUsageDetails property
     */
    get queryBranchRecognitionUsageDetails(): QueryBranchRecognitionUsageDetailsRequestBuilder;
    /**
     * The QueryBranchRecognitionUsageSummary property
     */
    get queryBranchRecognitionUsageSummary(): QueryBranchRecognitionUsageSummaryRequestBuilder;
    /**
     * The QueryBranchSourceRecognitionDetails property
     */
    get queryBranchSourceRecognitionDetails(): QueryBranchSourceRecognitionDetailsRequestBuilder;
    /**
     * The QueryBranchSourceRecognitionSummary property
     */
    get queryBranchSourceRecognitionSummary(): QueryBranchSourceRecognitionSummaryRequestBuilder;
    /**
     * The QueryEffectiveMedicalStandardCatalog property
     */
    get queryEffectiveMedicalStandardCatalog(): QueryEffectiveMedicalStandardCatalogRequestBuilder;
    /**
     * The QueryMedicalReportList property
     */
    get queryMedicalReportList(): QueryMedicalReportListRequestBuilder;
    /**
     * The QueryMedicalReportVersionDetail property
     */
    get queryMedicalReportVersionDetail(): QueryMedicalReportVersionDetailRequestBuilder;
    /**
     * The QueryMedicalReportVersionList property
     */
    get queryMedicalReportVersionList(): QueryMedicalReportVersionListRequestBuilder;
    /**
     * The QueryMedicalStandardCategoryList property
     */
    get queryMedicalStandardCategoryList(): QueryMedicalStandardCategoryListRequestBuilder;
    /**
     * The QueryMedicalStandardGroupList property
     */
    get queryMedicalStandardGroupList(): QueryMedicalStandardGroupListRequestBuilder;
    /**
     * The QueryMedicalStandardItemList property
     */
    get queryMedicalStandardItemList(): QueryMedicalStandardItemListRequestBuilder;
    /**
     * The QueryRecognitionAmountList property
     */
    get queryRecognitionAmountList(): QueryRecognitionAmountListRequestBuilder;
    /**
     * The QueryRecognitionCitationDetail property
     */
    get queryRecognitionCitationDetail(): QueryRecognitionCitationDetailRequestBuilder;
    /**
     * The QueryRecognitionMatchRecord property
     */
    get queryRecognitionMatchRecord(): QueryRecognitionMatchRecordRequestBuilder;
    /**
     * The QueryRecognitionProjectConfigurationList property
     */
    get queryRecognitionProjectConfigurationList(): QueryRecognitionProjectConfigurationListRequestBuilder;
    /**
     * The QueryRecognitionUsageDetails property
     */
    get queryRecognitionUsageDetails(): QueryRecognitionUsageDetailsRequestBuilder;
    /**
     * The QueryRecognitionUsageSummary property
     */
    get queryRecognitionUsageSummary(): QueryRecognitionUsageSummaryRequestBuilder;
    /**
     * The QuerySourceRecognitionDetails property
     */
    get querySourceRecognitionDetails(): QuerySourceRecognitionDetailsRequestBuilder;
    /**
     * The QuerySourceRecognitionSummary property
     */
    get querySourceRecognitionSummary(): QuerySourceRecognitionSummaryRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MedicalRecognitionReportQueryRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MedicalRecognitionReportQueryRequestBuilderNavigationMetadata: Record<Exclude<keyof MedicalRecognitionReportQueryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    queryBranchMedicalReportList: {
        requestsMetadata: QueryBranchMedicalReportListRequestBuilderRequestsMetadata,
    },
    queryBranchRecognitionAmountList: {
        requestsMetadata: QueryBranchRecognitionAmountListRequestBuilderRequestsMetadata,
    },
    queryBranchRecognitionUsageDetails: {
        requestsMetadata: QueryBranchRecognitionUsageDetailsRequestBuilderRequestsMetadata,
    },
    queryBranchRecognitionUsageSummary: {
        requestsMetadata: QueryBranchRecognitionUsageSummaryRequestBuilderRequestsMetadata,
    },
    queryBranchSourceRecognitionDetails: {
        requestsMetadata: QueryBranchSourceRecognitionDetailsRequestBuilderRequestsMetadata,
    },
    queryBranchSourceRecognitionSummary: {
        requestsMetadata: QueryBranchSourceRecognitionSummaryRequestBuilderRequestsMetadata,
    },
    queryEffectiveMedicalStandardCatalog: {
        requestsMetadata: QueryEffectiveMedicalStandardCatalogRequestBuilderRequestsMetadata,
    },
    queryMedicalReportList: {
        requestsMetadata: QueryMedicalReportListRequestBuilderRequestsMetadata,
    },
    queryMedicalReportVersionDetail: {
        requestsMetadata: QueryMedicalReportVersionDetailRequestBuilderRequestsMetadata,
    },
    queryMedicalReportVersionList: {
        requestsMetadata: QueryMedicalReportVersionListRequestBuilderRequestsMetadata,
    },
    queryMedicalStandardCategoryList: {
        requestsMetadata: QueryMedicalStandardCategoryListRequestBuilderRequestsMetadata,
    },
    queryMedicalStandardGroupList: {
        requestsMetadata: QueryMedicalStandardGroupListRequestBuilderRequestsMetadata,
    },
    queryMedicalStandardItemList: {
        requestsMetadata: QueryMedicalStandardItemListRequestBuilderRequestsMetadata,
    },
    queryRecognitionAmountList: {
        requestsMetadata: QueryRecognitionAmountListRequestBuilderRequestsMetadata,
    },
    queryRecognitionCitationDetail: {
        requestsMetadata: QueryRecognitionCitationDetailRequestBuilderRequestsMetadata,
    },
    queryRecognitionMatchRecord: {
        requestsMetadata: QueryRecognitionMatchRecordRequestBuilderRequestsMetadata,
    },
    queryRecognitionProjectConfigurationList: {
        requestsMetadata: QueryRecognitionProjectConfigurationListRequestBuilderRequestsMetadata,
    },
    queryRecognitionUsageDetails: {
        requestsMetadata: QueryRecognitionUsageDetailsRequestBuilderRequestsMetadata,
    },
    queryRecognitionUsageSummary: {
        requestsMetadata: QueryRecognitionUsageSummaryRequestBuilderRequestsMetadata,
    },
    querySourceRecognitionDetails: {
        requestsMetadata: QuerySourceRecognitionDetailsRequestBuilderRequestsMetadata,
    },
    querySourceRecognitionSummary: {
        requestsMetadata: QuerySourceRecognitionSummaryRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
