/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { QueryBranchMedicalReportListRequestBuilderRequestsMetadata, type QueryBranchMedicalReportListRequestBuilder } from './queryBranchMedicalReportList/index.js';
// @ts-ignore
import { QueryBranchRecognitionAmountListRequestBuilderRequestsMetadata, type QueryBranchRecognitionAmountListRequestBuilder } from './queryBranchRecognitionAmountList/index.js';
// @ts-ignore
import { QueryEffectiveMedicalStandardCatalogRequestBuilderRequestsMetadata, type QueryEffectiveMedicalStandardCatalogRequestBuilder } from './queryEffectiveMedicalStandardCatalog/index.js';
// @ts-ignore
import { QueryMedicalReportListRequestBuilderRequestsMetadata, type QueryMedicalReportListRequestBuilder } from './queryMedicalReportList/index.js';
// @ts-ignore
import { QueryMedicalReportVersionDetailRequestBuilderRequestsMetadata, type QueryMedicalReportVersionDetailRequestBuilder } from './queryMedicalReportVersionDetail/index.js';
// @ts-ignore
import { QueryMedicalReportVersionListRequestBuilderRequestsMetadata, type QueryMedicalReportVersionListRequestBuilder } from './queryMedicalReportVersionList/index.js';
// @ts-ignore
import { QueryMedicalStandardCategoryListRequestBuilderRequestsMetadata, type QueryMedicalStandardCategoryListRequestBuilder } from './queryMedicalStandardCategoryList/index.js';
// @ts-ignore
import { QueryMedicalStandardGroupListRequestBuilderRequestsMetadata, type QueryMedicalStandardGroupListRequestBuilder } from './queryMedicalStandardGroupList/index.js';
// @ts-ignore
import { QueryMedicalStandardItemListRequestBuilderRequestsMetadata, type QueryMedicalStandardItemListRequestBuilder } from './queryMedicalStandardItemList/index.js';
// @ts-ignore
import { QueryRecognitionAmountListRequestBuilderRequestsMetadata, type QueryRecognitionAmountListRequestBuilder } from './queryRecognitionAmountList/index.js';
// @ts-ignore
import { QueryRecognitionProjectConfigurationListRequestBuilderRequestsMetadata, type QueryRecognitionProjectConfigurationListRequestBuilder } from './queryRecognitionProjectConfigurationList/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery
 */
export interface MedicalRecognitionReportQueryRequestBuilder extends BaseRequestBuilder<MedicalRecognitionReportQueryRequestBuilder> {
    /**
     * The QueryBranchMedicalReportList property
     */
    get queryBranchMedicalReportList(): QueryBranchMedicalReportListRequestBuilder;
    /**
     * The QueryBranchRecognitionAmountList property
     */
    get queryBranchRecognitionAmountList(): QueryBranchRecognitionAmountListRequestBuilder;
    /**
     * The QueryEffectiveMedicalStandardCatalog property
     */
    get queryEffectiveMedicalStandardCatalog(): QueryEffectiveMedicalStandardCatalogRequestBuilder;
    /**
     * The QueryMedicalReportList property
     */
    get queryMedicalReportList(): QueryMedicalReportListRequestBuilder;
    /**
     * The QueryMedicalReportVersionDetail property
     */
    get queryMedicalReportVersionDetail(): QueryMedicalReportVersionDetailRequestBuilder;
    /**
     * The QueryMedicalReportVersionList property
     */
    get queryMedicalReportVersionList(): QueryMedicalReportVersionListRequestBuilder;
    /**
     * The QueryMedicalStandardCategoryList property
     */
    get queryMedicalStandardCategoryList(): QueryMedicalStandardCategoryListRequestBuilder;
    /**
     * The QueryMedicalStandardGroupList property
     */
    get queryMedicalStandardGroupList(): QueryMedicalStandardGroupListRequestBuilder;
    /**
     * The QueryMedicalStandardItemList property
     */
    get queryMedicalStandardItemList(): QueryMedicalStandardItemListRequestBuilder;
    /**
     * The QueryRecognitionAmountList property
     */
    get queryRecognitionAmountList(): QueryRecognitionAmountListRequestBuilder;
    /**
     * The QueryRecognitionProjectConfigurationList property
     */
    get queryRecognitionProjectConfigurationList(): QueryRecognitionProjectConfigurationListRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MedicalRecognitionReportQueryRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MedicalRecognitionReportQueryRequestBuilderNavigationMetadata: Record<Exclude<keyof MedicalRecognitionReportQueryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    queryBranchMedicalReportList: {
        requestsMetadata: QueryBranchMedicalReportListRequestBuilderRequestsMetadata,
    },
    queryBranchRecognitionAmountList: {
        requestsMetadata: QueryBranchRecognitionAmountListRequestBuilderRequestsMetadata,
    },
    queryEffectiveMedicalStandardCatalog: {
        requestsMetadata: QueryEffectiveMedicalStandardCatalogRequestBuilderRequestsMetadata,
    },
    queryMedicalReportList: {
        requestsMetadata: QueryMedicalReportListRequestBuilderRequestsMetadata,
    },
    queryMedicalReportVersionDetail: {
        requestsMetadata: QueryMedicalReportVersionDetailRequestBuilderRequestsMetadata,
    },
    queryMedicalReportVersionList: {
        requestsMetadata: QueryMedicalReportVersionListRequestBuilderRequestsMetadata,
    },
    queryMedicalStandardCategoryList: {
        requestsMetadata: QueryMedicalStandardCategoryListRequestBuilderRequestsMetadata,
    },
    queryMedicalStandardGroupList: {
        requestsMetadata: QueryMedicalStandardGroupListRequestBuilderRequestsMetadata,
    },
    queryMedicalStandardItemList: {
        requestsMetadata: QueryMedicalStandardItemListRequestBuilderRequestsMetadata,
    },
    queryRecognitionAmountList: {
        requestsMetadata: QueryRecognitionAmountListRequestBuilderRequestsMetadata,
    },
    queryRecognitionProjectConfigurationList: {
        requestsMetadata: QueryRecognitionProjectConfigurationListRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
