/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { QueryEffectiveMedicalStandardCatalogRequestBuilderRequestsMetadata, type QueryEffectiveMedicalStandardCatalogRequestBuilder } from './queryEffectiveMedicalStandardCatalog/index.js';
// @ts-ignore
import { QueryMedicalStandardCategoryListRequestBuilderRequestsMetadata, type QueryMedicalStandardCategoryListRequestBuilder } from './queryMedicalStandardCategoryList/index.js';
// @ts-ignore
import { QueryMedicalStandardGroupListRequestBuilderRequestsMetadata, type QueryMedicalStandardGroupListRequestBuilder } from './queryMedicalStandardGroupList/index.js';
// @ts-ignore
import { QueryMedicalStandardItemListRequestBuilderRequestsMetadata, type QueryMedicalStandardItemListRequestBuilder } from './queryMedicalStandardItemList/index.js';
// @ts-ignore
import { QueryRecognitionProjectConfigurationListRequestBuilderRequestsMetadata, type QueryRecognitionProjectConfigurationListRequestBuilder } from './queryRecognitionProjectConfigurationList/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery
 */
export interface MedicalRecognitionReportQueryRequestBuilder extends BaseRequestBuilder<MedicalRecognitionReportQueryRequestBuilder> {
    /**
     * The QueryEffectiveMedicalStandardCatalog property
     */
    get queryEffectiveMedicalStandardCatalog(): QueryEffectiveMedicalStandardCatalogRequestBuilder;
    /**
     * The QueryMedicalStandardCategoryList property
     */
    get queryMedicalStandardCategoryList(): QueryMedicalStandardCategoryListRequestBuilder;
    /**
     * The QueryMedicalStandardGroupList property
     */
    get queryMedicalStandardGroupList(): QueryMedicalStandardGroupListRequestBuilder;
    /**
     * The QueryMedicalStandardItemList property
     */
    get queryMedicalStandardItemList(): QueryMedicalStandardItemListRequestBuilder;
    /**
     * The QueryRecognitionProjectConfigurationList property
     */
    get queryRecognitionProjectConfigurationList(): QueryRecognitionProjectConfigurationListRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MedicalRecognitionReportQueryRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MedicalRecognitionReportQueryRequestBuilderNavigationMetadata: Record<Exclude<keyof MedicalRecognitionReportQueryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    queryEffectiveMedicalStandardCatalog: {
        requestsMetadata: QueryEffectiveMedicalStandardCatalogRequestBuilderRequestsMetadata,
    },
    queryMedicalStandardCategoryList: {
        requestsMetadata: QueryMedicalStandardCategoryListRequestBuilderRequestsMetadata,
    },
    queryMedicalStandardGroupList: {
        requestsMetadata: QueryMedicalStandardGroupListRequestBuilderRequestsMetadata,
    },
    queryMedicalStandardItemList: {
        requestsMetadata: QueryMedicalStandardItemListRequestBuilderRequestsMetadata,
    },
    queryRecognitionProjectConfigurationList: {
        requestsMetadata: QueryRecognitionProjectConfigurationListRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
