/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageResultDtoOfRecognitionUsageDetailReadModelFromDiscriminatorValue, serializeBranchRecognitionUsageDetailsQueryRequest, serializePageResultDtoOfRecognitionUsageDetailReadModel, type BranchRecognitionUsageDetailsQueryRequest, type PageResultDtoOfRecognitionUsageDetailReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryBranchRecognitionUsageDetails
 */
export interface QueryBranchRecognitionUsageDetailsRequestBuilder extends BaseRequestBuilder<QueryBranchRecognitionUsageDetailsRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageResultDtoOfRecognitionUsageDetailReadModel>}
     */
     post(body: BranchRecognitionUsageDetailsQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PageResultDtoOfRecognitionUsageDetailReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BranchRecognitionUsageDetailsQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryBranchRecognitionUsageDetailsRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryBranchRecognitionUsageDetails";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryBranchRecognitionUsageDetailsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryBranchRecognitionUsageDetailsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPageResultDtoOfRecognitionUsageDetailReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBranchRecognitionUsageDetailsQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
