/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRecognitionAmountReadModelFromDiscriminatorValue, serializeRecognitionAmountListQueryRequest, serializeRecognitionAmountReadModel, type RecognitionAmountListQueryRequest, type RecognitionAmountReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryRecognitionAmountList
 */
export interface QueryRecognitionAmountListRequestBuilder extends BaseRequestBuilder<QueryRecognitionAmountListRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecognitionAmountReadModel[]>}
     */
     post(body: RecognitionAmountListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecognitionAmountReadModel[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RecognitionAmountListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryRecognitionAmountListRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryRecognitionAmountList";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryRecognitionAmountListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryRecognitionAmountListRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createRecognitionAmountReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRecognitionAmountListQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
