/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { serializeSaveOrganizationHospitalBranchRecognitionAmountRequest, type SaveOrganizationHospitalBranchRecognitionAmountRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReport/SaveOrganizationHospitalBranchRecognitionAmount
 */
export interface SaveOrganizationHospitalBranchRecognitionAmountRequestBuilder extends BaseRequestBuilder<SaveOrganizationHospitalBranchRecognitionAmountRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<boolean>}
     */
     post(body: SaveOrganizationHospitalBranchRecognitionAmountRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<boolean | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SaveOrganizationHospitalBranchRecognitionAmountRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SaveOrganizationHospitalBranchRecognitionAmountRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReport/SaveOrganizationHospitalBranchRecognitionAmount";
/**
 * Metadata for all the requests in the request builder.
 */
export const SaveOrganizationHospitalBranchRecognitionAmountRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SaveOrganizationHospitalBranchRecognitionAmountRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "boolean",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSaveOrganizationHospitalBranchRecognitionAmountRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
