/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageResultDtoOfMedicalReportListReadModelFromDiscriminatorValue, serializeBranchReportListQueryRequest, serializePageResultDtoOfMedicalReportListReadModel, type BranchReportListQueryRequest, type PageResultDtoOfMedicalReportListReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryBranchMedicalReportList
 */
export interface QueryBranchMedicalReportListRequestBuilder extends BaseRequestBuilder<QueryBranchMedicalReportListRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageResultDtoOfMedicalReportListReadModel>}
     */
     post(body: BranchReportListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PageResultDtoOfMedicalReportListReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BranchReportListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryBranchMedicalReportListRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryBranchMedicalReportList";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryBranchMedicalReportListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryBranchMedicalReportListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPageResultDtoOfMedicalReportListReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBranchReportListQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
