/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageResultDtoOfSourceRecognitionSummaryReadModelFromDiscriminatorValue, serializeBranchSourceRecognitionSummaryQueryRequest, serializePageResultDtoOfSourceRecognitionSummaryReadModel, type BranchSourceRecognitionSummaryQueryRequest, type PageResultDtoOfSourceRecognitionSummaryReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryBranchSourceRecognitionSummary
 */
export interface QueryBranchSourceRecognitionSummaryRequestBuilder extends BaseRequestBuilder<QueryBranchSourceRecognitionSummaryRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageResultDtoOfSourceRecognitionSummaryReadModel>}
     */
     post(body: BranchSourceRecognitionSummaryQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PageResultDtoOfSourceRecognitionSummaryReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BranchSourceRecognitionSummaryQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryBranchSourceRecognitionSummaryRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryBranchSourceRecognitionSummary";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryBranchSourceRecognitionSummaryRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryBranchSourceRecognitionSummaryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPageResultDtoOfSourceRecognitionSummaryReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBranchSourceRecognitionSummaryQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
