/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ExaminationReportRequestBuilderRequestsMetadata, type ExaminationReportRequestBuilder } from './examinationReport/index.js';
// @ts-ignore
import { type WithReportItemRequestBuilder, WithReportItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { LaboratoryReportRequestBuilderRequestsMetadata, type LaboratoryReportRequestBuilder } from './laboratoryReport/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/report-pdf
 */
export interface ReportPdfRequestBuilder extends BaseRequestBuilder<ReportPdfRequestBuilder> {
    /**
     * The examinationReport property
     */
    get examinationReport(): ExaminationReportRequestBuilder;
    /**
     * The laboratoryReport property
     */
    get laboratoryReport(): LaboratoryReportRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.v1.reportPdf.item collection
     * @param reportId Unique identifier of the item
     * @returns {WithReportItemRequestBuilder}
     */
     byReportId(reportId: Guid) : WithReportItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ReportPdfRequestBuilderUriTemplate = "{+baseurl}/api/v1/report-pdf";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ReportPdfRequestBuilderNavigationMetadata: Record<Exclude<keyof ReportPdfRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byReportId: {
        navigationMetadata: WithReportItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["reportId"],
    },
    examinationReport: {
        requestsMetadata: ExaminationReportRequestBuilderRequestsMetadata,
    },
    laboratoryReport: {
        requestsMetadata: LaboratoryReportRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
