/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithReportVersionItemRequestBuilder, WithReportVersionItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/report-pdf/{reportId}/versions
 */
export interface VersionsRequestBuilder extends BaseRequestBuilder<VersionsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.v1.reportPdf.item.versions.item collection
     * @param reportVersionId Unique identifier of the item
     * @returns {WithReportVersionItemRequestBuilder}
     */
     byReportVersionId(reportVersionId: Guid) : WithReportVersionItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const VersionsRequestBuilderUriTemplate = "{+baseurl}/api/v1/report-pdf/{reportId}/versions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const VersionsRequestBuilderNavigationMetadata: Record<Exclude<keyof VersionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byReportVersionId: {
        navigationMetadata: WithReportVersionItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["reportVersionId"],
    },
};
/* tslint:enable */
/* eslint-enable */
