/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRecognitionMatchRecordReadModelFromDiscriminatorValue, serializeRecognitionMatchRecordQueryRequest, serializeRecognitionMatchRecordReadModel, type RecognitionMatchRecordQueryRequest, type RecognitionMatchRecordReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryRecognitionMatchRecord
 */
export interface QueryRecognitionMatchRecordRequestBuilder extends BaseRequestBuilder<QueryRecognitionMatchRecordRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecognitionMatchRecordReadModel>}
     */
     post(body: RecognitionMatchRecordQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecognitionMatchRecordReadModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RecognitionMatchRecordQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryRecognitionMatchRecordRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryRecognitionMatchRecord";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryRecognitionMatchRecordRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryRecognitionMatchRecordRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createRecognitionMatchRecordReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRecognitionMatchRecordQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
