/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface ChangeMedicalStandardItemRemarkRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The remark property
     */
    remark?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChangeMedicalStandardItemRemarkRequest}
 */
// @ts-ignore
export function createChangeMedicalStandardItemRemarkRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChangeMedicalStandardItemRemarkRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateMedicalStandardCategoryRequest}
 */
// @ts-ignore
export function createCreateMedicalStandardCategoryRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateMedicalStandardCategoryRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateMedicalStandardGroupRequest}
 */
// @ts-ignore
export function createCreateMedicalStandardGroupRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateMedicalStandardGroupRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateMedicalStandardItemRequest}
 */
// @ts-ignore
export function createCreateMedicalStandardItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateMedicalStandardItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateMutualRecognitionItemRequest}
 */
// @ts-ignore
export function createCreateMutualRecognitionItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateMutualRecognitionItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DisableMedicalStandardCategoryRequest}
 */
// @ts-ignore
export function createDisableMedicalStandardCategoryRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDisableMedicalStandardCategoryRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DisableMedicalStandardGroupRequest}
 */
// @ts-ignore
export function createDisableMedicalStandardGroupRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDisableMedicalStandardGroupRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DisableMedicalStandardItemRequest}
 */
// @ts-ignore
export function createDisableMedicalStandardItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDisableMedicalStandardItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DisableMutualRecognitionItemRequest}
 */
// @ts-ignore
export function createDisableMutualRecognitionItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDisableMutualRecognitionItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EffectiveMedicalStandardCatalogCategoryReadModel}
 */
// @ts-ignore
export function createEffectiveMedicalStandardCatalogCategoryReadModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEffectiveMedicalStandardCatalogCategoryReadModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EffectiveMedicalStandardCatalogGroupReadModel}
 */
// @ts-ignore
export function createEffectiveMedicalStandardCatalogGroupReadModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEffectiveMedicalStandardCatalogGroupReadModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EffectiveMedicalStandardCatalogItemReadModel}
 */
// @ts-ignore
export function createEffectiveMedicalStandardCatalogItemReadModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEffectiveMedicalStandardCatalogItemReadModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1 | MedicalItemType}
 */
// @ts-ignore
export function createEffectiveMedicalStandardCatalogQueryRequest_itemTypeFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEffectiveMedicalStandardCatalogQueryRequest_itemType;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1}
 */
// @ts-ignore
export function createEffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EffectiveMedicalStandardCatalogQueryRequest}
 */
// @ts-ignore
export function createEffectiveMedicalStandardCatalogQueryRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEffectiveMedicalStandardCatalogQueryRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EffectiveMedicalStandardCatalogReadModel}
 */
// @ts-ignore
export function createEffectiveMedicalStandardCatalogReadModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEffectiveMedicalStandardCatalogReadModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EffectiveMedicalStandardCatalogTypeReadModel}
 */
// @ts-ignore
export function createEffectiveMedicalStandardCatalogTypeReadModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEffectiveMedicalStandardCatalogTypeReadModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EnableMedicalStandardCategoryRequest}
 */
// @ts-ignore
export function createEnableMedicalStandardCategoryRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEnableMedicalStandardCategoryRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EnableMedicalStandardGroupRequest}
 */
// @ts-ignore
export function createEnableMedicalStandardGroupRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEnableMedicalStandardGroupRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EnableMedicalStandardItemRequest}
 */
// @ts-ignore
export function createEnableMedicalStandardItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEnableMedicalStandardItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EnableMutualRecognitionItemRequest}
 */
// @ts-ignore
export function createEnableMutualRecognitionItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEnableMutualRecognitionItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MedicalItemType}
 */
// @ts-ignore
export function createMedicalItemTypeFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMedicalItemType;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MedicalItemType | MedicalStandardCategoryListQueryRequest_itemTypeMember1}
 */
// @ts-ignore
export function createMedicalStandardCategoryListQueryRequest_itemTypeFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMedicalStandardCategoryListQueryRequest_itemType;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MedicalStandardCategoryListQueryRequest_itemTypeMember1}
 */
// @ts-ignore
export function createMedicalStandardCategoryListQueryRequest_itemTypeMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMedicalStandardCategoryListQueryRequest_itemTypeMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MedicalStandardCategoryListQueryRequest}
 */
// @ts-ignore
export function createMedicalStandardCategoryListQueryRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMedicalStandardCategoryListQueryRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MedicalStandardCategoryListReadModel}
 */
// @ts-ignore
export function createMedicalStandardCategoryListReadModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMedicalStandardCategoryListReadModel;
}
export interface CreateMedicalStandardCategoryRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The itemType property
     */
    itemType?: number | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The remark property
     */
    remark?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MedicalStandardGroupListQueryRequest}
 */
// @ts-ignore
export function createMedicalStandardGroupListQueryRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMedicalStandardGroupListQueryRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MedicalStandardGroupListReadModel}
 */
// @ts-ignore
export function createMedicalStandardGroupListReadModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMedicalStandardGroupListReadModel;
}
export interface CreateMedicalStandardGroupRequest extends AdditionalDataHolder, Parsable {
    /**
     * The categoryId property
     */
    categoryId?: Guid | null;
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The remark property
     */
    remark?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MedicalStandardItemListQueryRequest}
 */
// @ts-ignore
export function createMedicalStandardItemListQueryRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMedicalStandardItemListQueryRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MedicalStandardItemListReadModel}
 */
// @ts-ignore
export function createMedicalStandardItemListReadModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoMedicalStandardItemListReadModel;
}
export interface CreateMedicalStandardItemRequest extends AdditionalDataHolder, Parsable {
    /**
     * The categoryId property
     */
    categoryId?: Guid | null;
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The groupId property
     */
    groupId?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The remark property
     */
    remark?: string | null;
}
export interface CreateMutualRecognitionItemRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The organizationCode property
     */
    organizationCode?: string | null;
    /**
     * The recognitionDurationDays property
     */
    recognitionDurationDays?: number | null;
    /**
     * The standardProjectCode property
     */
    standardProjectCode?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateMedicalStandardCategoryRequest}
 */
// @ts-ignore
export function createUpdateMedicalStandardCategoryRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateMedicalStandardCategoryRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateMedicalStandardGroupRequest}
 */
// @ts-ignore
export function createUpdateMedicalStandardGroupRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateMedicalStandardGroupRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateMutualRecognitionItemConfigurationRequest}
 */
// @ts-ignore
export function createUpdateMutualRecognitionItemConfigurationRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateMutualRecognitionItemConfigurationRequest;
}
/**
 * The deserialization information for the current model
 * @param ChangeMedicalStandardItemRemarkRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChangeMedicalStandardItemRemarkRequest(changeMedicalStandardItemRemarkRequest: Partial<ChangeMedicalStandardItemRemarkRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { changeMedicalStandardItemRemarkRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { changeMedicalStandardItemRemarkRequest.id = n.getGuidValue(); },
        "remark": n => { changeMedicalStandardItemRemarkRequest.remark = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateMedicalStandardCategoryRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateMedicalStandardCategoryRequest(createMedicalStandardCategoryRequest: Partial<CreateMedicalStandardCategoryRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { createMedicalStandardCategoryRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "itemType": n => { createMedicalStandardCategoryRequest.itemType = n.getNumberValue(); },
        "name": n => { createMedicalStandardCategoryRequest.name = n.getStringValue(); },
        "remark": n => { createMedicalStandardCategoryRequest.remark = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateMedicalStandardGroupRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateMedicalStandardGroupRequest(createMedicalStandardGroupRequest: Partial<CreateMedicalStandardGroupRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryId": n => { createMedicalStandardGroupRequest.categoryId = n.getGuidValue(); },
        "changedProperties": n => { createMedicalStandardGroupRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "name": n => { createMedicalStandardGroupRequest.name = n.getStringValue(); },
        "remark": n => { createMedicalStandardGroupRequest.remark = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateMedicalStandardItemRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateMedicalStandardItemRequest(createMedicalStandardItemRequest: Partial<CreateMedicalStandardItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryId": n => { createMedicalStandardItemRequest.categoryId = n.getGuidValue(); },
        "changedProperties": n => { createMedicalStandardItemRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "code": n => { createMedicalStandardItemRequest.code = n.getStringValue(); },
        "groupId": n => { createMedicalStandardItemRequest.groupId = n.getGuidValue(); },
        "name": n => { createMedicalStandardItemRequest.name = n.getStringValue(); },
        "remark": n => { createMedicalStandardItemRequest.remark = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateMutualRecognitionItemRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateMutualRecognitionItemRequest(createMutualRecognitionItemRequest: Partial<CreateMutualRecognitionItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { createMutualRecognitionItemRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "organizationCode": n => { createMutualRecognitionItemRequest.organizationCode = n.getStringValue(); },
        "recognitionDurationDays": n => { createMutualRecognitionItemRequest.recognitionDurationDays = n.getNumberValue(); },
        "standardProjectCode": n => { createMutualRecognitionItemRequest.standardProjectCode = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DisableMedicalStandardCategoryRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDisableMedicalStandardCategoryRequest(disableMedicalStandardCategoryRequest: Partial<DisableMedicalStandardCategoryRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { disableMedicalStandardCategoryRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { disableMedicalStandardCategoryRequest.id = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DisableMedicalStandardGroupRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDisableMedicalStandardGroupRequest(disableMedicalStandardGroupRequest: Partial<DisableMedicalStandardGroupRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { disableMedicalStandardGroupRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { disableMedicalStandardGroupRequest.id = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DisableMedicalStandardItemRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDisableMedicalStandardItemRequest(disableMedicalStandardItemRequest: Partial<DisableMedicalStandardItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { disableMedicalStandardItemRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { disableMedicalStandardItemRequest.id = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DisableMutualRecognitionItemRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDisableMutualRecognitionItemRequest(disableMutualRecognitionItemRequest: Partial<DisableMutualRecognitionItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { disableMutualRecognitionItemRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { disableMutualRecognitionItemRequest.id = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EffectiveMedicalStandardCatalogCategoryReadModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEffectiveMedicalStandardCatalogCategoryReadModel(effectiveMedicalStandardCatalogCategoryReadModel: Partial<EffectiveMedicalStandardCatalogCategoryReadModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryName": n => { effectiveMedicalStandardCatalogCategoryReadModel.categoryName = n.getStringValue(); },
        "groups": n => { effectiveMedicalStandardCatalogCategoryReadModel.groups = n.getCollectionOfObjectValues<EffectiveMedicalStandardCatalogGroupReadModel>(createEffectiveMedicalStandardCatalogGroupReadModelFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param EffectiveMedicalStandardCatalogGroupReadModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEffectiveMedicalStandardCatalogGroupReadModel(effectiveMedicalStandardCatalogGroupReadModel: Partial<EffectiveMedicalStandardCatalogGroupReadModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "groupName": n => { effectiveMedicalStandardCatalogGroupReadModel.groupName = n.getStringValue(); },
        "items": n => { effectiveMedicalStandardCatalogGroupReadModel.items = n.getCollectionOfObjectValues<EffectiveMedicalStandardCatalogItemReadModel>(createEffectiveMedicalStandardCatalogItemReadModelFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param EffectiveMedicalStandardCatalogItemReadModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEffectiveMedicalStandardCatalogItemReadModel(effectiveMedicalStandardCatalogItemReadModel: Partial<EffectiveMedicalStandardCatalogItemReadModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { effectiveMedicalStandardCatalogItemReadModel.code = n.getStringValue(); },
        "name": n => { effectiveMedicalStandardCatalogItemReadModel.name = n.getStringValue(); },
        "operId": n => { effectiveMedicalStandardCatalogItemReadModel.operId = n.getGuidValue(); },
        "operTime": n => { effectiveMedicalStandardCatalogItemReadModel.operTime = n.getDateValue(); },
        "remark": n => { effectiveMedicalStandardCatalogItemReadModel.remark = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EffectiveMedicalStandardCatalogQueryRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEffectiveMedicalStandardCatalogQueryRequest(effectiveMedicalStandardCatalogQueryRequest: Partial<EffectiveMedicalStandardCatalogQueryRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryName": n => { effectiveMedicalStandardCatalogQueryRequest.categoryName = n.getStringValue(); },
        "itemType": n => { effectiveMedicalStandardCatalogQueryRequest.itemType = n.getObjectValue<EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1>(createEffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1FromDiscriminatorValue) ?? n.getObjectValue<MedicalItemType>(createMedicalItemTypeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param EffectiveMedicalStandardCatalogQueryRequest_itemType The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEffectiveMedicalStandardCatalogQueryRequest_itemType(effectiveMedicalStandardCatalogQueryRequest_itemType: Partial<EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1 | MedicalItemType> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoEffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1(effectiveMedicalStandardCatalogQueryRequest_itemType as EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1),
        ...deserializeIntoMedicalItemType(effectiveMedicalStandardCatalogQueryRequest_itemType as MedicalItemType),
    }
}
/**
 * The deserialization information for the current model
 * @param EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1(effectiveMedicalStandardCatalogQueryRequest_itemTypeMember1: Partial<EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param EffectiveMedicalStandardCatalogReadModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEffectiveMedicalStandardCatalogReadModel(effectiveMedicalStandardCatalogReadModel: Partial<EffectiveMedicalStandardCatalogReadModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "itemTypes": n => { effectiveMedicalStandardCatalogReadModel.itemTypes = n.getCollectionOfObjectValues<EffectiveMedicalStandardCatalogTypeReadModel>(createEffectiveMedicalStandardCatalogTypeReadModelFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param EffectiveMedicalStandardCatalogTypeReadModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEffectiveMedicalStandardCatalogTypeReadModel(effectiveMedicalStandardCatalogTypeReadModel: Partial<EffectiveMedicalStandardCatalogTypeReadModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categories": n => { effectiveMedicalStandardCatalogTypeReadModel.categories = n.getCollectionOfObjectValues<EffectiveMedicalStandardCatalogCategoryReadModel>(createEffectiveMedicalStandardCatalogCategoryReadModelFromDiscriminatorValue); },
        "itemType": n => { effectiveMedicalStandardCatalogTypeReadModel.itemType = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EnableMedicalStandardCategoryRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEnableMedicalStandardCategoryRequest(enableMedicalStandardCategoryRequest: Partial<EnableMedicalStandardCategoryRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { enableMedicalStandardCategoryRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { enableMedicalStandardCategoryRequest.id = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EnableMedicalStandardGroupRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEnableMedicalStandardGroupRequest(enableMedicalStandardGroupRequest: Partial<EnableMedicalStandardGroupRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { enableMedicalStandardGroupRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { enableMedicalStandardGroupRequest.id = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EnableMedicalStandardItemRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEnableMedicalStandardItemRequest(enableMedicalStandardItemRequest: Partial<EnableMedicalStandardItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { enableMedicalStandardItemRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { enableMedicalStandardItemRequest.id = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EnableMutualRecognitionItemRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEnableMutualRecognitionItemRequest(enableMutualRecognitionItemRequest: Partial<EnableMutualRecognitionItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { enableMutualRecognitionItemRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { enableMutualRecognitionItemRequest.id = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MedicalItemType The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMedicalItemType(medicalItemType: Partial<MedicalItemType> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param MedicalStandardCategoryListQueryRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMedicalStandardCategoryListQueryRequest(medicalStandardCategoryListQueryRequest: Partial<MedicalStandardCategoryListQueryRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "itemType": n => { medicalStandardCategoryListQueryRequest.itemType = n.getObjectValue<MedicalItemType>(createMedicalItemTypeFromDiscriminatorValue) ?? n.getObjectValue<MedicalStandardCategoryListQueryRequest_itemTypeMember1>(createMedicalStandardCategoryListQueryRequest_itemTypeMember1FromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param MedicalStandardCategoryListQueryRequest_itemType The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMedicalStandardCategoryListQueryRequest_itemType(medicalStandardCategoryListQueryRequest_itemType: Partial<MedicalItemType | MedicalStandardCategoryListQueryRequest_itemTypeMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoMedicalItemType(medicalStandardCategoryListQueryRequest_itemType as MedicalItemType),
        ...deserializeIntoMedicalStandardCategoryListQueryRequest_itemTypeMember1(medicalStandardCategoryListQueryRequest_itemType as MedicalStandardCategoryListQueryRequest_itemTypeMember1),
    }
}
/**
 * The deserialization information for the current model
 * @param MedicalStandardCategoryListQueryRequest_itemTypeMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMedicalStandardCategoryListQueryRequest_itemTypeMember1(medicalStandardCategoryListQueryRequest_itemTypeMember1: Partial<MedicalStandardCategoryListQueryRequest_itemTypeMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param MedicalStandardCategoryListReadModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMedicalStandardCategoryListReadModel(medicalStandardCategoryListReadModel: Partial<MedicalStandardCategoryListReadModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryId": n => { medicalStandardCategoryListReadModel.categoryId = n.getGuidValue(); },
        "isValid": n => { medicalStandardCategoryListReadModel.isValid = n.getBooleanValue(); },
        "itemType": n => { medicalStandardCategoryListReadModel.itemType = n.getNumberValue(); },
        "name": n => { medicalStandardCategoryListReadModel.name = n.getStringValue(); },
        "remark": n => { medicalStandardCategoryListReadModel.remark = n.getStringValue(); },
        "usageStatus": n => { medicalStandardCategoryListReadModel.usageStatus = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MedicalStandardGroupListQueryRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMedicalStandardGroupListQueryRequest(medicalStandardGroupListQueryRequest: Partial<MedicalStandardGroupListQueryRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryId": n => { medicalStandardGroupListQueryRequest.categoryId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MedicalStandardGroupListReadModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMedicalStandardGroupListReadModel(medicalStandardGroupListReadModel: Partial<MedicalStandardGroupListReadModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryId": n => { medicalStandardGroupListReadModel.categoryId = n.getGuidValue(); },
        "groupId": n => { medicalStandardGroupListReadModel.groupId = n.getGuidValue(); },
        "isValid": n => { medicalStandardGroupListReadModel.isValid = n.getBooleanValue(); },
        "name": n => { medicalStandardGroupListReadModel.name = n.getStringValue(); },
        "remark": n => { medicalStandardGroupListReadModel.remark = n.getStringValue(); },
        "usageStatus": n => { medicalStandardGroupListReadModel.usageStatus = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MedicalStandardItemListQueryRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMedicalStandardItemListQueryRequest(medicalStandardItemListQueryRequest: Partial<MedicalStandardItemListQueryRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryId": n => { medicalStandardItemListQueryRequest.categoryId = n.getGuidValue(); },
        "code": n => { medicalStandardItemListQueryRequest.code = n.getStringValue(); },
        "groupId": n => { medicalStandardItemListQueryRequest.groupId = n.getGuidValue(); },
        "isValid": n => { medicalStandardItemListQueryRequest.isValid = n.getBooleanValue(); },
        "name": n => { medicalStandardItemListQueryRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param MedicalStandardItemListReadModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMedicalStandardItemListReadModel(medicalStandardItemListReadModel: Partial<MedicalStandardItemListReadModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryId": n => { medicalStandardItemListReadModel.categoryId = n.getGuidValue(); },
        "code": n => { medicalStandardItemListReadModel.code = n.getStringValue(); },
        "groupId": n => { medicalStandardItemListReadModel.groupId = n.getGuidValue(); },
        "isValid": n => { medicalStandardItemListReadModel.isValid = n.getBooleanValue(); },
        "itemId": n => { medicalStandardItemListReadModel.itemId = n.getGuidValue(); },
        "itemType": n => { medicalStandardItemListReadModel.itemType = n.getNumberValue(); },
        "name": n => { medicalStandardItemListReadModel.name = n.getStringValue(); },
        "remark": n => { medicalStandardItemListReadModel.remark = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateMedicalStandardCategoryRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateMedicalStandardCategoryRequest(updateMedicalStandardCategoryRequest: Partial<UpdateMedicalStandardCategoryRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { updateMedicalStandardCategoryRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { updateMedicalStandardCategoryRequest.id = n.getGuidValue(); },
        "itemType": n => { updateMedicalStandardCategoryRequest.itemType = n.getNumberValue(); },
        "name": n => { updateMedicalStandardCategoryRequest.name = n.getStringValue(); },
        "remark": n => { updateMedicalStandardCategoryRequest.remark = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateMedicalStandardGroupRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateMedicalStandardGroupRequest(updateMedicalStandardGroupRequest: Partial<UpdateMedicalStandardGroupRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { updateMedicalStandardGroupRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { updateMedicalStandardGroupRequest.id = n.getGuidValue(); },
        "name": n => { updateMedicalStandardGroupRequest.name = n.getStringValue(); },
        "remark": n => { updateMedicalStandardGroupRequest.remark = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateMutualRecognitionItemConfigurationRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateMutualRecognitionItemConfigurationRequest(updateMutualRecognitionItemConfigurationRequest: Partial<UpdateMutualRecognitionItemConfigurationRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "changedProperties": n => { updateMutualRecognitionItemConfigurationRequest.changedProperties = n.getCollectionOfPrimitiveValues<string>("string"); },
        "id": n => { updateMutualRecognitionItemConfigurationRequest.id = n.getGuidValue(); },
        "recognitionDurationDays": n => { updateMutualRecognitionItemConfigurationRequest.recognitionDurationDays = n.getNumberValue(); },
    }
}
export interface DisableMedicalStandardCategoryRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
}
export interface DisableMedicalStandardGroupRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
}
export interface DisableMedicalStandardItemRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
}
export interface DisableMutualRecognitionItemRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
}
export interface EffectiveMedicalStandardCatalogCategoryReadModel extends AdditionalDataHolder, Parsable {
    /**
     * The categoryName property
     */
    categoryName?: string | null;
    /**
     * The groups property
     */
    groups?: EffectiveMedicalStandardCatalogGroupReadModel[] | null;
}
export interface EffectiveMedicalStandardCatalogGroupReadModel extends AdditionalDataHolder, Parsable {
    /**
     * The groupName property
     */
    groupName?: string | null;
    /**
     * The items property
     */
    items?: EffectiveMedicalStandardCatalogItemReadModel[] | null;
}
export interface EffectiveMedicalStandardCatalogItemReadModel extends AdditionalDataHolder, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The operId property
     */
    operId?: Guid | null;
    /**
     * The operTime property
     */
    operTime?: Date | null;
    /**
     * The remark property
     */
    remark?: string | null;
}
export interface EffectiveMedicalStandardCatalogQueryRequest extends AdditionalDataHolder, Parsable {
    /**
     * The categoryName property
     */
    categoryName?: string | null;
    /**
     * The itemType property
     */
    itemType?: EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1 | MedicalItemType | null;
}
export type EffectiveMedicalStandardCatalogQueryRequest_itemType = EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1 | MedicalItemType;
export interface EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1 extends AdditionalDataHolder, Parsable {
}
export interface EffectiveMedicalStandardCatalogReadModel extends AdditionalDataHolder, Parsable {
    /**
     * The itemTypes property
     */
    itemTypes?: EffectiveMedicalStandardCatalogTypeReadModel[] | null;
}
export interface EffectiveMedicalStandardCatalogTypeReadModel extends AdditionalDataHolder, Parsable {
    /**
     * The categories property
     */
    categories?: EffectiveMedicalStandardCatalogCategoryReadModel[] | null;
    /**
     * The itemType property
     */
    itemType?: number | null;
}
export interface EnableMedicalStandardCategoryRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
}
export interface EnableMedicalStandardGroupRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
}
export interface EnableMedicalStandardItemRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
}
export interface EnableMutualRecognitionItemRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
}
export interface MedicalItemType extends AdditionalDataHolder, Parsable {
}
export interface MedicalStandardCategoryListQueryRequest extends AdditionalDataHolder, Parsable {
    /**
     * The itemType property
     */
    itemType?: MedicalItemType | MedicalStandardCategoryListQueryRequest_itemTypeMember1 | null;
}
export type MedicalStandardCategoryListQueryRequest_itemType = MedicalItemType | MedicalStandardCategoryListQueryRequest_itemTypeMember1;
export interface MedicalStandardCategoryListQueryRequest_itemTypeMember1 extends AdditionalDataHolder, Parsable {
}
export interface MedicalStandardCategoryListReadModel extends AdditionalDataHolder, Parsable {
    /**
     * The categoryId property
     */
    categoryId?: Guid | null;
    /**
     * The isValid property
     */
    isValid?: boolean | null;
    /**
     * The itemType property
     */
    itemType?: number | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The remark property
     */
    remark?: string | null;
    /**
     * The usageStatus property
     */
    usageStatus?: number | null;
}
export interface MedicalStandardGroupListQueryRequest extends AdditionalDataHolder, Parsable {
    /**
     * The categoryId property
     */
    categoryId?: Guid | null;
}
export interface MedicalStandardGroupListReadModel extends AdditionalDataHolder, Parsable {
    /**
     * The categoryId property
     */
    categoryId?: Guid | null;
    /**
     * The groupId property
     */
    groupId?: Guid | null;
    /**
     * The isValid property
     */
    isValid?: boolean | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The remark property
     */
    remark?: string | null;
    /**
     * The usageStatus property
     */
    usageStatus?: number | null;
}
export interface MedicalStandardItemListQueryRequest extends AdditionalDataHolder, Parsable {
    /**
     * The categoryId property
     */
    categoryId?: Guid | null;
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The groupId property
     */
    groupId?: Guid | null;
    /**
     * The isValid property
     */
    isValid?: boolean | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface MedicalStandardItemListReadModel extends AdditionalDataHolder, Parsable {
    /**
     * The categoryId property
     */
    categoryId?: Guid | null;
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The groupId property
     */
    groupId?: Guid | null;
    /**
     * The isValid property
     */
    isValid?: boolean | null;
    /**
     * The itemId property
     */
    itemId?: Guid | null;
    /**
     * The itemType property
     */
    itemType?: number | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The remark property
     */
    remark?: string | null;
}
/**
 * Serializes information the current object
 * @param ChangeMedicalStandardItemRemarkRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChangeMedicalStandardItemRemarkRequest(writer: SerializationWriter, changeMedicalStandardItemRemarkRequest: Partial<ChangeMedicalStandardItemRemarkRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!changeMedicalStandardItemRemarkRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", changeMedicalStandardItemRemarkRequest.changedProperties);
    writer.writeGuidValue("id", changeMedicalStandardItemRemarkRequest.id);
    writer.writeStringValue("remark", changeMedicalStandardItemRemarkRequest.remark);
    writer.writeAdditionalData(changeMedicalStandardItemRemarkRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateMedicalStandardCategoryRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateMedicalStandardCategoryRequest(writer: SerializationWriter, createMedicalStandardCategoryRequest: Partial<CreateMedicalStandardCategoryRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createMedicalStandardCategoryRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", createMedicalStandardCategoryRequest.changedProperties);
    writer.writeNumberValue("itemType", createMedicalStandardCategoryRequest.itemType);
    writer.writeStringValue("name", createMedicalStandardCategoryRequest.name);
    writer.writeStringValue("remark", createMedicalStandardCategoryRequest.remark);
    writer.writeAdditionalData(createMedicalStandardCategoryRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateMedicalStandardGroupRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateMedicalStandardGroupRequest(writer: SerializationWriter, createMedicalStandardGroupRequest: Partial<CreateMedicalStandardGroupRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createMedicalStandardGroupRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("categoryId", createMedicalStandardGroupRequest.categoryId);
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", createMedicalStandardGroupRequest.changedProperties);
    writer.writeStringValue("name", createMedicalStandardGroupRequest.name);
    writer.writeStringValue("remark", createMedicalStandardGroupRequest.remark);
    writer.writeAdditionalData(createMedicalStandardGroupRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateMedicalStandardItemRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateMedicalStandardItemRequest(writer: SerializationWriter, createMedicalStandardItemRequest: Partial<CreateMedicalStandardItemRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createMedicalStandardItemRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("categoryId", createMedicalStandardItemRequest.categoryId);
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", createMedicalStandardItemRequest.changedProperties);
    writer.writeStringValue("code", createMedicalStandardItemRequest.code);
    writer.writeGuidValue("groupId", createMedicalStandardItemRequest.groupId);
    writer.writeStringValue("name", createMedicalStandardItemRequest.name);
    writer.writeStringValue("remark", createMedicalStandardItemRequest.remark);
    writer.writeAdditionalData(createMedicalStandardItemRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateMutualRecognitionItemRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateMutualRecognitionItemRequest(writer: SerializationWriter, createMutualRecognitionItemRequest: Partial<CreateMutualRecognitionItemRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createMutualRecognitionItemRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", createMutualRecognitionItemRequest.changedProperties);
    writer.writeStringValue("organizationCode", createMutualRecognitionItemRequest.organizationCode);
    writer.writeNumberValue("recognitionDurationDays", createMutualRecognitionItemRequest.recognitionDurationDays);
    writer.writeStringValue("standardProjectCode", createMutualRecognitionItemRequest.standardProjectCode);
    writer.writeAdditionalData(createMutualRecognitionItemRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param DisableMedicalStandardCategoryRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDisableMedicalStandardCategoryRequest(writer: SerializationWriter, disableMedicalStandardCategoryRequest: Partial<DisableMedicalStandardCategoryRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!disableMedicalStandardCategoryRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", disableMedicalStandardCategoryRequest.changedProperties);
    writer.writeGuidValue("id", disableMedicalStandardCategoryRequest.id);
    writer.writeAdditionalData(disableMedicalStandardCategoryRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param DisableMedicalStandardGroupRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDisableMedicalStandardGroupRequest(writer: SerializationWriter, disableMedicalStandardGroupRequest: Partial<DisableMedicalStandardGroupRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!disableMedicalStandardGroupRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", disableMedicalStandardGroupRequest.changedProperties);
    writer.writeGuidValue("id", disableMedicalStandardGroupRequest.id);
    writer.writeAdditionalData(disableMedicalStandardGroupRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param DisableMedicalStandardItemRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDisableMedicalStandardItemRequest(writer: SerializationWriter, disableMedicalStandardItemRequest: Partial<DisableMedicalStandardItemRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!disableMedicalStandardItemRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", disableMedicalStandardItemRequest.changedProperties);
    writer.writeGuidValue("id", disableMedicalStandardItemRequest.id);
    writer.writeAdditionalData(disableMedicalStandardItemRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param DisableMutualRecognitionItemRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDisableMutualRecognitionItemRequest(writer: SerializationWriter, disableMutualRecognitionItemRequest: Partial<DisableMutualRecognitionItemRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!disableMutualRecognitionItemRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", disableMutualRecognitionItemRequest.changedProperties);
    writer.writeGuidValue("id", disableMutualRecognitionItemRequest.id);
    writer.writeAdditionalData(disableMutualRecognitionItemRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param EffectiveMedicalStandardCatalogCategoryReadModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEffectiveMedicalStandardCatalogCategoryReadModel(writer: SerializationWriter, effectiveMedicalStandardCatalogCategoryReadModel: Partial<EffectiveMedicalStandardCatalogCategoryReadModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!effectiveMedicalStandardCatalogCategoryReadModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("categoryName", effectiveMedicalStandardCatalogCategoryReadModel.categoryName);
    writer.writeCollectionOfObjectValues<EffectiveMedicalStandardCatalogGroupReadModel>("groups", effectiveMedicalStandardCatalogCategoryReadModel.groups, serializeEffectiveMedicalStandardCatalogGroupReadModel);
    writer.writeAdditionalData(effectiveMedicalStandardCatalogCategoryReadModel.additionalData);
}
/**
 * Serializes information the current object
 * @param EffectiveMedicalStandardCatalogGroupReadModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEffectiveMedicalStandardCatalogGroupReadModel(writer: SerializationWriter, effectiveMedicalStandardCatalogGroupReadModel: Partial<EffectiveMedicalStandardCatalogGroupReadModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!effectiveMedicalStandardCatalogGroupReadModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("groupName", effectiveMedicalStandardCatalogGroupReadModel.groupName);
    writer.writeCollectionOfObjectValues<EffectiveMedicalStandardCatalogItemReadModel>("items", effectiveMedicalStandardCatalogGroupReadModel.items, serializeEffectiveMedicalStandardCatalogItemReadModel);
    writer.writeAdditionalData(effectiveMedicalStandardCatalogGroupReadModel.additionalData);
}
/**
 * Serializes information the current object
 * @param EffectiveMedicalStandardCatalogItemReadModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEffectiveMedicalStandardCatalogItemReadModel(writer: SerializationWriter, effectiveMedicalStandardCatalogItemReadModel: Partial<EffectiveMedicalStandardCatalogItemReadModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!effectiveMedicalStandardCatalogItemReadModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", effectiveMedicalStandardCatalogItemReadModel.code);
    writer.writeStringValue("name", effectiveMedicalStandardCatalogItemReadModel.name);
    writer.writeGuidValue("operId", effectiveMedicalStandardCatalogItemReadModel.operId);
    writer.writeDateValue("operTime", effectiveMedicalStandardCatalogItemReadModel.operTime);
    writer.writeStringValue("remark", effectiveMedicalStandardCatalogItemReadModel.remark);
    writer.writeAdditionalData(effectiveMedicalStandardCatalogItemReadModel.additionalData);
}
/**
 * Serializes information the current object
 * @param EffectiveMedicalStandardCatalogQueryRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEffectiveMedicalStandardCatalogQueryRequest(writer: SerializationWriter, effectiveMedicalStandardCatalogQueryRequest: Partial<EffectiveMedicalStandardCatalogQueryRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!effectiveMedicalStandardCatalogQueryRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("categoryName", effectiveMedicalStandardCatalogQueryRequest.categoryName);
    writer.writeObjectValue<EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1 | MedicalItemType>("itemType", effectiveMedicalStandardCatalogQueryRequest.itemType, serializeEffectiveMedicalStandardCatalogQueryRequest_itemType);
    writer.writeAdditionalData(effectiveMedicalStandardCatalogQueryRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param EffectiveMedicalStandardCatalogQueryRequest_itemType The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEffectiveMedicalStandardCatalogQueryRequest_itemType(writer: SerializationWriter, effectiveMedicalStandardCatalogQueryRequest_itemType: Partial<EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1 | MedicalItemType> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeEffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1(writer, effectiveMedicalStandardCatalogQueryRequest_itemType as EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1);
    serializeMedicalItemType(writer, effectiveMedicalStandardCatalogQueryRequest_itemType as MedicalItemType);
}
/**
 * Serializes information the current object
 * @param EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1 The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1(writer: SerializationWriter, effectiveMedicalStandardCatalogQueryRequest_itemTypeMember1: Partial<EffectiveMedicalStandardCatalogQueryRequest_itemTypeMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!effectiveMedicalStandardCatalogQueryRequest_itemTypeMember1 || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(effectiveMedicalStandardCatalogQueryRequest_itemTypeMember1.additionalData);
}
/**
 * Serializes information the current object
 * @param EffectiveMedicalStandardCatalogReadModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEffectiveMedicalStandardCatalogReadModel(writer: SerializationWriter, effectiveMedicalStandardCatalogReadModel: Partial<EffectiveMedicalStandardCatalogReadModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!effectiveMedicalStandardCatalogReadModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<EffectiveMedicalStandardCatalogTypeReadModel>("itemTypes", effectiveMedicalStandardCatalogReadModel.itemTypes, serializeEffectiveMedicalStandardCatalogTypeReadModel);
    writer.writeAdditionalData(effectiveMedicalStandardCatalogReadModel.additionalData);
}
/**
 * Serializes information the current object
 * @param EffectiveMedicalStandardCatalogTypeReadModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEffectiveMedicalStandardCatalogTypeReadModel(writer: SerializationWriter, effectiveMedicalStandardCatalogTypeReadModel: Partial<EffectiveMedicalStandardCatalogTypeReadModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!effectiveMedicalStandardCatalogTypeReadModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<EffectiveMedicalStandardCatalogCategoryReadModel>("categories", effectiveMedicalStandardCatalogTypeReadModel.categories, serializeEffectiveMedicalStandardCatalogCategoryReadModel);
    writer.writeNumberValue("itemType", effectiveMedicalStandardCatalogTypeReadModel.itemType);
    writer.writeAdditionalData(effectiveMedicalStandardCatalogTypeReadModel.additionalData);
}
/**
 * Serializes information the current object
 * @param EnableMedicalStandardCategoryRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEnableMedicalStandardCategoryRequest(writer: SerializationWriter, enableMedicalStandardCategoryRequest: Partial<EnableMedicalStandardCategoryRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!enableMedicalStandardCategoryRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", enableMedicalStandardCategoryRequest.changedProperties);
    writer.writeGuidValue("id", enableMedicalStandardCategoryRequest.id);
    writer.writeAdditionalData(enableMedicalStandardCategoryRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param EnableMedicalStandardGroupRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEnableMedicalStandardGroupRequest(writer: SerializationWriter, enableMedicalStandardGroupRequest: Partial<EnableMedicalStandardGroupRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!enableMedicalStandardGroupRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", enableMedicalStandardGroupRequest.changedProperties);
    writer.writeGuidValue("id", enableMedicalStandardGroupRequest.id);
    writer.writeAdditionalData(enableMedicalStandardGroupRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param EnableMedicalStandardItemRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEnableMedicalStandardItemRequest(writer: SerializationWriter, enableMedicalStandardItemRequest: Partial<EnableMedicalStandardItemRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!enableMedicalStandardItemRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", enableMedicalStandardItemRequest.changedProperties);
    writer.writeGuidValue("id", enableMedicalStandardItemRequest.id);
    writer.writeAdditionalData(enableMedicalStandardItemRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param EnableMutualRecognitionItemRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEnableMutualRecognitionItemRequest(writer: SerializationWriter, enableMutualRecognitionItemRequest: Partial<EnableMutualRecognitionItemRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!enableMutualRecognitionItemRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", enableMutualRecognitionItemRequest.changedProperties);
    writer.writeGuidValue("id", enableMutualRecognitionItemRequest.id);
    writer.writeAdditionalData(enableMutualRecognitionItemRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MedicalItemType The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMedicalItemType(writer: SerializationWriter, medicalItemType: Partial<MedicalItemType> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!medicalItemType || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(medicalItemType.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MedicalStandardCategoryListQueryRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMedicalStandardCategoryListQueryRequest(writer: SerializationWriter, medicalStandardCategoryListQueryRequest: Partial<MedicalStandardCategoryListQueryRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!medicalStandardCategoryListQueryRequest || isSerializingDerivedType) { return; }
    writer.writeObjectValue<MedicalItemType | MedicalStandardCategoryListQueryRequest_itemTypeMember1>("itemType", medicalStandardCategoryListQueryRequest.itemType, serializeMedicalStandardCategoryListQueryRequest_itemType);
    writer.writeAdditionalData(medicalStandardCategoryListQueryRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MedicalStandardCategoryListQueryRequest_itemType The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMedicalStandardCategoryListQueryRequest_itemType(writer: SerializationWriter, medicalStandardCategoryListQueryRequest_itemType: Partial<MedicalItemType | MedicalStandardCategoryListQueryRequest_itemTypeMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeMedicalItemType(writer, medicalStandardCategoryListQueryRequest_itemType as MedicalItemType);
    serializeMedicalStandardCategoryListQueryRequest_itemTypeMember1(writer, medicalStandardCategoryListQueryRequest_itemType as MedicalStandardCategoryListQueryRequest_itemTypeMember1);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MedicalStandardCategoryListQueryRequest_itemTypeMember1 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMedicalStandardCategoryListQueryRequest_itemTypeMember1(writer: SerializationWriter, medicalStandardCategoryListQueryRequest_itemTypeMember1: Partial<MedicalStandardCategoryListQueryRequest_itemTypeMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!medicalStandardCategoryListQueryRequest_itemTypeMember1 || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(medicalStandardCategoryListQueryRequest_itemTypeMember1.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MedicalStandardCategoryListReadModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMedicalStandardCategoryListReadModel(writer: SerializationWriter, medicalStandardCategoryListReadModel: Partial<MedicalStandardCategoryListReadModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!medicalStandardCategoryListReadModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("categoryId", medicalStandardCategoryListReadModel.categoryId);
    writer.writeBooleanValue("isValid", medicalStandardCategoryListReadModel.isValid);
    writer.writeNumberValue("itemType", medicalStandardCategoryListReadModel.itemType);
    writer.writeStringValue("name", medicalStandardCategoryListReadModel.name);
    writer.writeStringValue("remark", medicalStandardCategoryListReadModel.remark);
    writer.writeNumberValue("usageStatus", medicalStandardCategoryListReadModel.usageStatus);
    writer.writeAdditionalData(medicalStandardCategoryListReadModel.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MedicalStandardGroupListQueryRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMedicalStandardGroupListQueryRequest(writer: SerializationWriter, medicalStandardGroupListQueryRequest: Partial<MedicalStandardGroupListQueryRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!medicalStandardGroupListQueryRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("categoryId", medicalStandardGroupListQueryRequest.categoryId);
    writer.writeAdditionalData(medicalStandardGroupListQueryRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MedicalStandardGroupListReadModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMedicalStandardGroupListReadModel(writer: SerializationWriter, medicalStandardGroupListReadModel: Partial<MedicalStandardGroupListReadModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!medicalStandardGroupListReadModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("categoryId", medicalStandardGroupListReadModel.categoryId);
    writer.writeGuidValue("groupId", medicalStandardGroupListReadModel.groupId);
    writer.writeBooleanValue("isValid", medicalStandardGroupListReadModel.isValid);
    writer.writeStringValue("name", medicalStandardGroupListReadModel.name);
    writer.writeStringValue("remark", medicalStandardGroupListReadModel.remark);
    writer.writeNumberValue("usageStatus", medicalStandardGroupListReadModel.usageStatus);
    writer.writeAdditionalData(medicalStandardGroupListReadModel.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MedicalStandardItemListQueryRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMedicalStandardItemListQueryRequest(writer: SerializationWriter, medicalStandardItemListQueryRequest: Partial<MedicalStandardItemListQueryRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!medicalStandardItemListQueryRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("categoryId", medicalStandardItemListQueryRequest.categoryId);
    writer.writeStringValue("code", medicalStandardItemListQueryRequest.code);
    writer.writeGuidValue("groupId", medicalStandardItemListQueryRequest.groupId);
    writer.writeBooleanValue("isValid", medicalStandardItemListQueryRequest.isValid);
    writer.writeStringValue("name", medicalStandardItemListQueryRequest.name);
    writer.writeAdditionalData(medicalStandardItemListQueryRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MedicalStandardItemListReadModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMedicalStandardItemListReadModel(writer: SerializationWriter, medicalStandardItemListReadModel: Partial<MedicalStandardItemListReadModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!medicalStandardItemListReadModel || isSerializingDerivedType) { return; }
    writer.writeGuidValue("categoryId", medicalStandardItemListReadModel.categoryId);
    writer.writeStringValue("code", medicalStandardItemListReadModel.code);
    writer.writeGuidValue("groupId", medicalStandardItemListReadModel.groupId);
    writer.writeBooleanValue("isValid", medicalStandardItemListReadModel.isValid);
    writer.writeGuidValue("itemId", medicalStandardItemListReadModel.itemId);
    writer.writeNumberValue("itemType", medicalStandardItemListReadModel.itemType);
    writer.writeStringValue("name", medicalStandardItemListReadModel.name);
    writer.writeStringValue("remark", medicalStandardItemListReadModel.remark);
    writer.writeAdditionalData(medicalStandardItemListReadModel.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateMedicalStandardCategoryRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateMedicalStandardCategoryRequest(writer: SerializationWriter, updateMedicalStandardCategoryRequest: Partial<UpdateMedicalStandardCategoryRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateMedicalStandardCategoryRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", updateMedicalStandardCategoryRequest.changedProperties);
    writer.writeGuidValue("id", updateMedicalStandardCategoryRequest.id);
    writer.writeNumberValue("itemType", updateMedicalStandardCategoryRequest.itemType);
    writer.writeStringValue("name", updateMedicalStandardCategoryRequest.name);
    writer.writeStringValue("remark", updateMedicalStandardCategoryRequest.remark);
    writer.writeAdditionalData(updateMedicalStandardCategoryRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateMedicalStandardGroupRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateMedicalStandardGroupRequest(writer: SerializationWriter, updateMedicalStandardGroupRequest: Partial<UpdateMedicalStandardGroupRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateMedicalStandardGroupRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", updateMedicalStandardGroupRequest.changedProperties);
    writer.writeGuidValue("id", updateMedicalStandardGroupRequest.id);
    writer.writeStringValue("name", updateMedicalStandardGroupRequest.name);
    writer.writeStringValue("remark", updateMedicalStandardGroupRequest.remark);
    writer.writeAdditionalData(updateMedicalStandardGroupRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateMutualRecognitionItemConfigurationRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateMutualRecognitionItemConfigurationRequest(writer: SerializationWriter, updateMutualRecognitionItemConfigurationRequest: Partial<UpdateMutualRecognitionItemConfigurationRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateMutualRecognitionItemConfigurationRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("changedProperties", updateMutualRecognitionItemConfigurationRequest.changedProperties);
    writer.writeGuidValue("id", updateMutualRecognitionItemConfigurationRequest.id);
    writer.writeNumberValue("recognitionDurationDays", updateMutualRecognitionItemConfigurationRequest.recognitionDurationDays);
    writer.writeAdditionalData(updateMutualRecognitionItemConfigurationRequest.additionalData);
}
export interface UpdateMedicalStandardCategoryRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The itemType property
     */
    itemType?: number | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The remark property
     */
    remark?: string | null;
}
export interface UpdateMedicalStandardGroupRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The remark property
     */
    remark?: string | null;
}
export interface UpdateMutualRecognitionItemConfigurationRequest extends AdditionalDataHolder, Parsable {
    /**
     * The changedProperties property
     */
    changedProperties?: string[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The recognitionDurationDays property
     */
    recognitionDurationDays?: number | null;
}
/* tslint:enable */
/* eslint-enable */
