/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMedicalReportVersionListReadModelFromDiscriminatorValue, serializeMedicalReportVersionListQueryRequest, serializeMedicalReportVersionListReadModel, type MedicalReportVersionListQueryRequest, type MedicalReportVersionListReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryMedicalReportVersionList
 */
export interface QueryMedicalReportVersionListRequestBuilder extends BaseRequestBuilder<QueryMedicalReportVersionListRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MedicalReportVersionListReadModel[]>}
     */
     post(body: MedicalReportVersionListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MedicalReportVersionListReadModel[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MedicalReportVersionListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryMedicalReportVersionListRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryMedicalReportVersionList";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryMedicalReportVersionListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryMedicalReportVersionListRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createMedicalReportVersionListReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMedicalReportVersionListQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
