/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMedicalStandardItemListReadModelFromDiscriminatorValue, serializeMedicalStandardItemListQueryRequest, serializeMedicalStandardItemListReadModel, type MedicalStandardItemListQueryRequest, type MedicalStandardItemListReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryMedicalStandardItemList
 */
export interface QueryMedicalStandardItemListRequestBuilder extends BaseRequestBuilder<QueryMedicalStandardItemListRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MedicalStandardItemListReadModel[]>}
     */
     post(body: MedicalStandardItemListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MedicalStandardItemListReadModel[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MedicalStandardItemListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryMedicalStandardItemListRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryMedicalStandardItemList";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryMedicalStandardItemListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryMedicalStandardItemListRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createMedicalStandardItemListReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMedicalStandardItemListQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
