/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChangeMedicalStandardItemRemarkRequestBuilderRequestsMetadata, type ChangeMedicalStandardItemRemarkRequestBuilder } from './changeMedicalStandardItemRemark/index.js';
// @ts-ignore
import { CreateMedicalStandardCategoryRequestBuilderRequestsMetadata, type CreateMedicalStandardCategoryRequestBuilder } from './createMedicalStandardCategory/index.js';
// @ts-ignore
import { CreateMedicalStandardGroupRequestBuilderRequestsMetadata, type CreateMedicalStandardGroupRequestBuilder } from './createMedicalStandardGroup/index.js';
// @ts-ignore
import { CreateMedicalStandardItemRequestBuilderRequestsMetadata, type CreateMedicalStandardItemRequestBuilder } from './createMedicalStandardItem/index.js';
// @ts-ignore
import { CreateMutualRecognitionItemRequestBuilderRequestsMetadata, type CreateMutualRecognitionItemRequestBuilder } from './createMutualRecognitionItem/index.js';
// @ts-ignore
import { DisableMedicalStandardCategoryRequestBuilderRequestsMetadata, type DisableMedicalStandardCategoryRequestBuilder } from './disableMedicalStandardCategory/index.js';
// @ts-ignore
import { DisableMedicalStandardGroupRequestBuilderRequestsMetadata, type DisableMedicalStandardGroupRequestBuilder } from './disableMedicalStandardGroup/index.js';
// @ts-ignore
import { DisableMedicalStandardItemRequestBuilderRequestsMetadata, type DisableMedicalStandardItemRequestBuilder } from './disableMedicalStandardItem/index.js';
// @ts-ignore
import { DisableMutualRecognitionItemRequestBuilderRequestsMetadata, type DisableMutualRecognitionItemRequestBuilder } from './disableMutualRecognitionItem/index.js';
// @ts-ignore
import { EnableMedicalStandardCategoryRequestBuilderRequestsMetadata, type EnableMedicalStandardCategoryRequestBuilder } from './enableMedicalStandardCategory/index.js';
// @ts-ignore
import { EnableMedicalStandardGroupRequestBuilderRequestsMetadata, type EnableMedicalStandardGroupRequestBuilder } from './enableMedicalStandardGroup/index.js';
// @ts-ignore
import { EnableMedicalStandardItemRequestBuilderRequestsMetadata, type EnableMedicalStandardItemRequestBuilder } from './enableMedicalStandardItem/index.js';
// @ts-ignore
import { EnableMutualRecognitionItemRequestBuilderRequestsMetadata, type EnableMutualRecognitionItemRequestBuilder } from './enableMutualRecognitionItem/index.js';
// @ts-ignore
import { SaveBranchRecognitionAmountRequestBuilderRequestsMetadata, type SaveBranchRecognitionAmountRequestBuilder } from './saveBranchRecognitionAmount/index.js';
// @ts-ignore
import { SaveOrganizationHospitalBranchRecognitionAmountRequestBuilderRequestsMetadata, type SaveOrganizationHospitalBranchRecognitionAmountRequestBuilder } from './saveOrganizationHospitalBranchRecognitionAmount/index.js';
// @ts-ignore
import { type UpdateMedicalStandardCategoryRequestBuilder, UpdateMedicalStandardCategoryRequestBuilderRequestsMetadata } from './updateMedicalStandardCategory/index.js';
// @ts-ignore
import { type UpdateMedicalStandardGroupRequestBuilder, UpdateMedicalStandardGroupRequestBuilderRequestsMetadata } from './updateMedicalStandardGroup/index.js';
// @ts-ignore
import { type UpdateMutualRecognitionItemConfigurationRequestBuilder, UpdateMutualRecognitionItemConfigurationRequestBuilderRequestsMetadata } from './updateMutualRecognitionItemConfiguration/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReport
 */
export interface MedicalRecognitionReportRequestBuilder extends BaseRequestBuilder<MedicalRecognitionReportRequestBuilder> {
    /**
     * The ChangeMedicalStandardItemRemark property
     */
    get changeMedicalStandardItemRemark(): ChangeMedicalStandardItemRemarkRequestBuilder;
    /**
     * The CreateMedicalStandardCategory property
     */
    get createMedicalStandardCategory(): CreateMedicalStandardCategoryRequestBuilder;
    /**
     * The CreateMedicalStandardGroup property
     */
    get createMedicalStandardGroup(): CreateMedicalStandardGroupRequestBuilder;
    /**
     * The CreateMedicalStandardItem property
     */
    get createMedicalStandardItem(): CreateMedicalStandardItemRequestBuilder;
    /**
     * The CreateMutualRecognitionItem property
     */
    get createMutualRecognitionItem(): CreateMutualRecognitionItemRequestBuilder;
    /**
     * The DisableMedicalStandardCategory property
     */
    get disableMedicalStandardCategory(): DisableMedicalStandardCategoryRequestBuilder;
    /**
     * The DisableMedicalStandardGroup property
     */
    get disableMedicalStandardGroup(): DisableMedicalStandardGroupRequestBuilder;
    /**
     * The DisableMedicalStandardItem property
     */
    get disableMedicalStandardItem(): DisableMedicalStandardItemRequestBuilder;
    /**
     * The DisableMutualRecognitionItem property
     */
    get disableMutualRecognitionItem(): DisableMutualRecognitionItemRequestBuilder;
    /**
     * The EnableMedicalStandardCategory property
     */
    get enableMedicalStandardCategory(): EnableMedicalStandardCategoryRequestBuilder;
    /**
     * The EnableMedicalStandardGroup property
     */
    get enableMedicalStandardGroup(): EnableMedicalStandardGroupRequestBuilder;
    /**
     * The EnableMedicalStandardItem property
     */
    get enableMedicalStandardItem(): EnableMedicalStandardItemRequestBuilder;
    /**
     * The EnableMutualRecognitionItem property
     */
    get enableMutualRecognitionItem(): EnableMutualRecognitionItemRequestBuilder;
    /**
     * The SaveBranchRecognitionAmount property
     */
    get saveBranchRecognitionAmount(): SaveBranchRecognitionAmountRequestBuilder;
    /**
     * The SaveOrganizationHospitalBranchRecognitionAmount property
     */
    get saveOrganizationHospitalBranchRecognitionAmount(): SaveOrganizationHospitalBranchRecognitionAmountRequestBuilder;
    /**
     * The UpdateMedicalStandardCategory property
     */
    get updateMedicalStandardCategory(): UpdateMedicalStandardCategoryRequestBuilder;
    /**
     * The UpdateMedicalStandardGroup property
     */
    get updateMedicalStandardGroup(): UpdateMedicalStandardGroupRequestBuilder;
    /**
     * The UpdateMutualRecognitionItemConfiguration property
     */
    get updateMutualRecognitionItemConfiguration(): UpdateMutualRecognitionItemConfigurationRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MedicalRecognitionReportRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReport";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MedicalRecognitionReportRequestBuilderNavigationMetadata: Record<Exclude<keyof MedicalRecognitionReportRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    changeMedicalStandardItemRemark: {
        requestsMetadata: ChangeMedicalStandardItemRemarkRequestBuilderRequestsMetadata,
    },
    createMedicalStandardCategory: {
        requestsMetadata: CreateMedicalStandardCategoryRequestBuilderRequestsMetadata,
    },
    createMedicalStandardGroup: {
        requestsMetadata: CreateMedicalStandardGroupRequestBuilderRequestsMetadata,
    },
    createMedicalStandardItem: {
        requestsMetadata: CreateMedicalStandardItemRequestBuilderRequestsMetadata,
    },
    createMutualRecognitionItem: {
        requestsMetadata: CreateMutualRecognitionItemRequestBuilderRequestsMetadata,
    },
    disableMedicalStandardCategory: {
        requestsMetadata: DisableMedicalStandardCategoryRequestBuilderRequestsMetadata,
    },
    disableMedicalStandardGroup: {
        requestsMetadata: DisableMedicalStandardGroupRequestBuilderRequestsMetadata,
    },
    disableMedicalStandardItem: {
        requestsMetadata: DisableMedicalStandardItemRequestBuilderRequestsMetadata,
    },
    disableMutualRecognitionItem: {
        requestsMetadata: DisableMutualRecognitionItemRequestBuilderRequestsMetadata,
    },
    enableMedicalStandardCategory: {
        requestsMetadata: EnableMedicalStandardCategoryRequestBuilderRequestsMetadata,
    },
    enableMedicalStandardGroup: {
        requestsMetadata: EnableMedicalStandardGroupRequestBuilderRequestsMetadata,
    },
    enableMedicalStandardItem: {
        requestsMetadata: EnableMedicalStandardItemRequestBuilderRequestsMetadata,
    },
    enableMutualRecognitionItem: {
        requestsMetadata: EnableMutualRecognitionItemRequestBuilderRequestsMetadata,
    },
    saveBranchRecognitionAmount: {
        requestsMetadata: SaveBranchRecognitionAmountRequestBuilderRequestsMetadata,
    },
    saveOrganizationHospitalBranchRecognitionAmount: {
        requestsMetadata: SaveOrganizationHospitalBranchRecognitionAmountRequestBuilderRequestsMetadata,
    },
    updateMedicalStandardCategory: {
        requestsMetadata: UpdateMedicalStandardCategoryRequestBuilderRequestsMetadata,
    },
    updateMedicalStandardGroup: {
        requestsMetadata: UpdateMedicalStandardGroupRequestBuilderRequestsMetadata,
    },
    updateMutualRecognitionItemConfiguration: {
        requestsMetadata: UpdateMutualRecognitionItemConfigurationRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
