/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMedicalStandardGroupListReadModelFromDiscriminatorValue, serializeMedicalStandardGroupListQueryRequest, serializeMedicalStandardGroupListReadModel, type MedicalStandardGroupListQueryRequest, type MedicalStandardGroupListReadModel } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReportQuery/QueryMedicalStandardGroupList
 */
export interface QueryMedicalStandardGroupListRequestBuilder extends BaseRequestBuilder<QueryMedicalStandardGroupListRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MedicalStandardGroupListReadModel[]>}
     */
     post(body: MedicalStandardGroupListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MedicalStandardGroupListReadModel[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MedicalStandardGroupListQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueryMedicalStandardGroupListRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReportQuery/QueryMedicalStandardGroupList";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryMedicalStandardGroupListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueryMedicalStandardGroupListRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createMedicalStandardGroupListReadModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMedicalStandardGroupListQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
