/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEnumMetadataItemDtoFromDiscriminatorValue, serializeEnumMetadataItemDto, serializeQueryEnumMetadataRequest, type EnumMetadataItemDto, type QueryEnumMetadataRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/EnumMetadata/GetEnumMetadata
 */
export interface GetEnumMetadataRequestBuilder extends BaseRequestBuilder<GetEnumMetadataRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EnumMetadataItemDto[]>}
     */
     post(body: QueryEnumMetadataRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EnumMetadataItemDto[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QueryEnumMetadataRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GetEnumMetadataRequestBuilderUriTemplate = "{+baseurl}/Api/EnumMetadata/GetEnumMetadata";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetEnumMetadataRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: GetEnumMetadataRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createEnumMetadataItemDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQueryEnumMetadataRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
