/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createReportPdfDownloadFromDiscriminatorValue, serializeMedicalReportVersionPdfQueryRequest, serializeReportPdfDownload, type MedicalReportVersionPdfQueryRequest, type ReportPdfDownload } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Api/MedicalRecognitionReport/OpenReportVersionPdf
 */
export interface OpenReportVersionPdfRequestBuilder extends BaseRequestBuilder<OpenReportVersionPdfRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ReportPdfDownload>}
     */
     post(body: MedicalReportVersionPdfQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ReportPdfDownload | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MedicalReportVersionPdfQueryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OpenReportVersionPdfRequestBuilderUriTemplate = "{+baseurl}/Api/MedicalRecognitionReport/OpenReportVersionPdf";
/**
 * Metadata for all the requests in the request builder.
 */
export const OpenReportVersionPdfRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: OpenReportVersionPdfRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createReportPdfDownloadFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMedicalReportVersionPdfQueryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
